import test from 'node:test';
import assert from 'node:assert/strict';
import {createRun} from '../src/game.js';
import {createPart,equip,unequip,stats} from '../src/assembly.js';
import {receiveHit,healthView,tickHealth,heal} from '../src/systems/health.js';
import {healthSegments} from '../src/ui/atoms.js';
const fixture=()=>{const s=createRun();s.body=createPart(s,'bastion');s.organs=[createPart(s,'armor'),createPart(s,'shield')];s.hp=stats(s).hp;s.organs[1].shieldCharge=1;return s;};
test('shield, two plates, then health; simultaneous hit ignored; healing does not repair armor',()=>{const s=fixture(),st=stats(s);for(const expected of ['shield','armor','armor','armor','armor','hurt']){assert.equal(receiveHit(s,st),expected);assert.equal(receiveHit(s,st),'ignored');s.time++;}assert.equal(s.hp,2);assert.equal(healthView(s,st.hp,st.armor).armor,0);heal(s,st.hp);assert.equal(s.hp,3);assert.equal(healthView(s,st.hp,st.armor).armor,0);s.time=100;tickHealth(s,st);assert.equal(healthView(s,st.hp,st.armor).armor,0);assert.equal(receiveHit(s,st),'shield');});
test('equipment removal and reinstallation cannot refill consumed plates',()=>{const s=fixture();s.organs[1]=null;const p=s.organs[0];for(let i=0;i<4;i++){receiveHit(s,stats(s));s.time++;}unequip(s,'organs',0);equip(s,p.id,0);assert.equal(healthView(s,stats(s).hp,stats(s).armor).armor,0);});
test('HUD keeps health cells after a plate is lost and distinguishes shield recharge',()=>{const s=fixture(),st=stats(s);const before=healthSegments(healthView(s,st.hp,st.armor));assert.equal((before.match(/is-armored/g)||[]).length,2);assert.match(before,/has-shield/);receiveHit(s,st);s.time++;receiveHit(s,st);const after=healthSegments(healthView(s,st.hp,st.armor));assert.equal((after.match(/is-full/g)||[]).length,3);assert.equal((after.match(/is-armored/g)||[]).length,2);assert.match(after,/is-half-armored/);assert.doesNotMatch(after,/has-shield/);});
test('armor remains bounded by living cells after a capacity change and critical HP is never repaired by armor',()=>{const s=fixture();s.hp=1;const st=stats(s),v=healthView(s,st.hp,st.armor);assert.equal(v.armor,1);assert.equal((healthSegments(v).match(/is-armored/g)||[]).length,1);s.organs[1]=null;assert.equal(receiveHit(s,st),'armor');assert.equal(s.hp,1);});

test('two hits remove the two halves of one plate while preserving underlying health',()=>{const s=fixture();s.organs[1]=null;const st=stats(s);receiveHit(s,st);assert.equal(healthView(s,st.hp,st.armor).armor,1.5);assert.match(healthSegments(healthView(s,st.hp,st.armor)),/is-half-armored/);s.time++;receiveHit(s,st);assert.equal(healthView(s,st.hp,st.armor).armor,1);assert.doesNotMatch(healthSegments(healthView(s,st.hp,st.armor)),/is-half-armored/);assert.equal(s.hp,3);});
test('shield perimeter tracks elapsed recharge time and remains complete when ready',()=>{const s=fixture(),st=stats(s);receiveHit(s,st);assert.equal(healthView(s,st.hp).shieldProgress,0);s.time=6;tickHealth(s,st);assert.equal(healthView(s,st.hp).shieldProgress,.5);assert.equal(healthView(s,st.hp).shield,false);s.time=12;tickHealth(s,st);assert.equal(healthView(s,st.hp).shieldProgress,1);assert.equal(healthView(s,st.hp).shield,true);});
