import test from 'node:test';
import assert from 'node:assert/strict';
import {createRun} from '../src/game.js';
import {createPart,equip,unequip,stats} from '../src/assembly.js';
import {receiveHit,healthView,tickHealth,heal} from '../src/systems/health.js';
import {healthSegments} from '../src/ui/atoms.js';
import {partArt} from '../src/ui/molecules.js';
const fixture=()=>{const s=createRun();s.body=createPart(s,'bastion');s.body.setId='hecaton';s.organs=[createPart(s,'armor'),createPart(s,'shield')];s.hp=stats(s).hp;s.organs[1].shieldCharge=1;return s;};
test('shield, two plates, then health; healing does not repair armor but armor plates do over time',()=>{const s=fixture(),st=stats(s),hits=[];for(let i=0;i<7;i++){hits.push(receiveHit(s,st));if(i<6)s.time++;}assert.deepEqual(hits,['shield','armor','armor','armor','armor','armor','hurt']);assert.equal(receiveHit(s,st),'ignored');assert.equal(s.hp,4);assert.equal(healthView(s,st.hp,st.armor).armor,0);heal(s,st.hp);assert.equal(s.hp,5);assert.equal(healthView(s,st.hp,st.armor).armor,0);s.time=15;tickHealth(s,st);assert.equal(healthView(s,st.hp,st.armor).armor,.5);assert.equal(receiveHit(s,st),'shield');});
test('equipment removal and reinstallation cannot refill consumed plates',()=>{const s=fixture();s.organs[1]=null;const p=s.organs[0];for(let i=0;i<4;i++){receiveHit(s,stats(s));s.time++;}unequip(s,'organs',0);equip(s,p.id,0);assert.equal(healthView(s,stats(s).hp,stats(s).armor).armor,.5);});
test('armor repair cycle is not reset by hits and only plates rebuild it',()=>{const s=fixture();s.organs=[createPart(s,'armor'),createPart(s,'repairGland')];let st=stats(s);assert.equal(st.armor,2.5);assert.equal(st.armorRepairAmount,.5,'the Repair Kit no longer patches plates');for(let i=0;i<5;i++){assert.equal(receiveHit(s,st),'armor');s.time+=1;}assert.equal(healthView(s,st.hp,st.armor).armor,0);s.time=14.9;assert.equal(receiveHit(s,st),'hurt');tickHealth(s,st);assert.equal(healthView(s,st.hp,st.armor).armor,0);s.time=15;tickHealth(s,st);assert.equal(healthView(s,st.hp,st.armor).armor,.5);const capacity=st.armor;s.organs=[createPart(s,'repairGland'),null];st=stats(s);assert.equal(st.armor,1.5);assert.equal(st.armorRepairAmount,0);assert.ok(st.armor<capacity);});
test('armor plate ranks add half a plate while the repair kit adds no armour at all',()=>{const s=createRun();s.body.tier=5;const plate=createPart(s,'armor'),gland=createPart(s,'repairGland');s.organs=[plate,null];for(const [tier,armor]of [[1,1.5],[2,2],[3,2.5],[4,3],[5,3.5]]){plate.tier=tier;assert.equal(stats(s).armor,armor);}s.organs=[gland,null];for(const tier of [1,2,3,4,5]){gland.tier=tier;assert.equal(stats(s).armorRepairAmount,0);assert.equal(stats(s).armor,.5);}assert.match(partArt('repairGland'),/repair-gland-v2\.png/);});
test('HUD keeps health cells after a plate is lost and distinguishes shield recharge',()=>{const s=fixture(),st=stats(s);const before=healthSegments(healthView(s,st.hp,st.armor));assert.equal((before.match(/is-armored/g)||[]).length,3);assert.match(before,/is-half-armored/);assert.match(before,/has-shield/);receiveHit(s,st);s.time++;receiveHit(s,st);const after=healthSegments(healthView(s,st.hp,st.armor));assert.equal((after.match(/is-full/g)||[]).length,5);assert.equal((after.match(/is-armored/g)||[]).length,3);assert.equal((after.match(/is-half-armored/g)||[]).length,2);assert.doesNotMatch(after,/has-shield/);});
test('armor remains bounded by living cells after a capacity change and critical HP is never repaired by armor',()=>{const s=fixture();s.hp=1;const st=stats(s),v=healthView(s,st.hp,st.armor);assert.equal(v.armor,1);assert.equal((healthSegments(v).match(/is-armored/g)||[]).length,1);s.organs[1]=null;assert.equal(receiveHit(s,st),'armor');assert.equal(s.hp,1);});

test('two hits remove the two halves of one plate while preserving underlying health',()=>{const s=fixture();s.organs[1]=null;const st=stats(s);receiveHit(s,st);assert.equal(healthView(s,st.hp,st.armor).armor,2);assert.equal((healthSegments(healthView(s,st.hp,st.armor)).match(/is-half-armored/g)||[]).length,2);s.time++;receiveHit(s,st);assert.equal(healthView(s,st.hp,st.armor).armor,1.5);assert.equal((healthSegments(healthView(s,st.hp,st.armor)).match(/is-half-armored/g)||[]).length,1);assert.equal(s.hp,5);});
test('shield perimeter tracks elapsed recharge time and remains complete when ready',()=>{const s=fixture(),st=stats(s);receiveHit(s,st);assert.equal(healthView(s,st.hp).shieldProgress,0);s.time=7.5;tickHealth(s,st);assert.equal(healthView(s,st.hp).shieldProgress,.5);assert.equal(healthView(s,st.hp).shield,false);s.time=15;tickHealth(s,st);assert.equal(healthView(s,st.hp).shieldProgress,1);assert.equal(healthView(s,st.hp).shield,true);});
