import test from 'node:test';
import assert from 'node:assert/strict';
import {createRun,step,attack,hurtEnemy,beginEncounter,randomLoot} from '../src/game.js';
import {createWorldRun} from '../src/world-run.js';
import {createPaintedRun} from '../src/painterly-stage.js';
import {createPart,equip,unequip,swapBody,stats,weaponStats,digest,upgradeOptions,newProfile} from '../src/assembly.js';
import {mutationView,isaacState,activeMutation,combatTime,hasOrgan,inMire} from '../src/systems/mutations.js';
import {prepareIsaacAttack,isaacHit,isaacDeath,conductorAttack,tickIsaacCombat,slimePace} from '../src/systems/isaac-combat.js';
import {heal,tickHealth,receiveHit} from '../src/systems/health.js';
import {prepareEncounters,discoverEncounters,takeDeal,claimEncounter,openSecret,challengeAllowed,tickChallenge,ENCOUNTERS} from '../src/systems/encounters.js';
import {cloneForComparison,unlockCondition} from '../src/ui/adapters.js';
import {compatibility,mutationWarning} from '../src/ui/isaac-ui.js';
function run(){const s=createRun(undefined,'survival',19);s.world={walkable:()=>true,chunk:()=>({cx:0,cz:0,lair:{x:999,z:999}})};s.encounters={nodes:[],active:null};s.rng=()=>.99;s.nextElite=s.nextBoss=1e9;return s;}
function gear(s,{arms=['seed'],organs=[],legs=['universal','universal']}={}){s.arms=arms.map(k=>createPart(s,k));s.organs=organs.map(k=>createPart(s,k));s.legs=legs.map(k=>createPart(s,k));return s;}
function enemy(s,{x=5,z=0,hp=1000,kind='normal',...rest}={}){const e={id:++s.entityId,x,z,hp,maxHp:hp,kind,armor:0,radius:.5,speed:0,contact:99,damage:1,born:0,xp:0,...rest};s.enemies.push(e);return e;}
function node(s,type){const n={id:'encounter-'+type,type,x:0,y:0,z:0,radius:ENCOUNTERS[type].radius||1,state:'ready',rewards:['slime','parasite','regen'],deals:['organs','fuse'],discovered:true,claimed:false};s.encounters.nodes.push(n);return n;}
test('distinct equipped family types activate together, inventory and duplicates do not count',()=>{const s=gear(run(),{arms:['acid'],organs:['slime','regen'],legs:['plated','plated']});assert(activeMutation(s,'mire'));s.inventory.push(createPart(s,'rocket'));assert(!activeMutation(s,'hive'));s.organs=[];assert.equal(mutationView(s).find(f=>f.id==='mire').count,2);});
test('switching equipment disables mutation without resetting combat counters',()=>{const s=gear(run(),{arms:['rocket','fangs'],organs:['digestion']});isaacState(s).hiveKills=4;assert(activeMutation(s,'hive'));const copy=cloneForComparison(s);assert(unequip(copy,'organs',0));assert.match(mutationWarning(s,copy),/Улей/);assert(unequip(s,'organs',0));assert(!activeMutation(s,'hive'));assert(equip(s,s.inventory[0].id,0));assert.equal(s.isaac.hiveKills,4);assert(activeMutation(s,'hive'));});
test('new behavior organs have no meaningless power upgrades and describe compatible hands',()=>{const s=gear(run(),{arms:['seed','acid']});for(const k of ['returnNerve','slime','parasite','commonNerve','outerStomach','reverseHeart'])assert.deepEqual(upgradeOptions(createPart(s,k)),[]);assert.match(compatibility(s,createPart(s,'returnNerve')),/Семенной/);assert.match(unlockCondition('reverseHeart'),/Редкая/);});
test('parasite counter belongs to each hand and repeats do not increment or infect',()=>{const s=gear(run(),{arms:['seed','seed'],organs:['parasite']});const [a,b]=s.arms;let w;for(let i=0;i<3;i++)w=prepareIsaacAttack(s,a,weaponStats(s,a));assert(w.isaac.parasite);assert(!prepareIsaacAttack(s,b,weaponStats(s,b)).isaac.parasite);assert(!prepareIsaacAttack(s,a,weaponStats(s,a),true).isaac.parasite);assert.equal(s.isaac.attacks[a.id],3);});
test('slime, infection and death combine, larvae cannot recursively reproduce',()=>{const s=gear(run(),{organs:['slime','parasite']});const e=enemy(s,{hp:1});const w={isaac:{slime:true,parasite:true}};isaacHit(s,e,100,w);hurtEnemy(s,e,1);assert.equal(s.isaac.larvae.length,2);assert.equal(s.isaac.slimePools.length,1);const target=enemy(s,{x:5,hp:1});isaacHit(s,target,100,w);tickIsaacCombat(s,1,(e,d,source)=>hurtEnemy(s,e,d,0,source));assert.equal(target.hp,0);assert.equal(s.isaac.larvae.length,1);tickIsaacCombat(s,5,()=>{});assert.equal(s.isaac.larvae.length,0);});
test('slime pools slow without damaging, infecting or extending corpse slime',()=>{const s=gear(run()),e=enemy(s);isaacState(s).slimePools.push({x:5,z:0,radius:2,life:3});assert.equal(slimePace(s,e),.75);assert.equal(slimePace(s,{...e,kind:'boss'}),.9);tickIsaacCombat(s,1,()=>assert.fail('no damage'));assert.equal(e.hp,1000);assert.equal(e.slimeUntil,undefined);});
test('expired clutch never spawns, persistent shots retain organ snapshots',()=>{const s=gear(run(),{organs:['parasite','slime']});const e=enemy(s);const w=prepareIsaacAttack(s,s.arms[0],weaponStats(s,s.arms[0]));s.organs=[];isaacHit(s,e,5,w);assert.equal(e.slimeUntil,3);e.clutch={until:1,damage:40};s.time=2;isaacDeath(s,e,'direct');assert.equal(s.isaac.larvae.length,0);});
test('returning projectile sweeps twice with 60% return damage without refunding rounds',()=>{const s=gear(run(),{organs:['returnNerve']});s.arms[0].key='needle';s.arms[0].ammo=1;const e=enemy(s);attack(s,0);const q=s.shots[0];q.w.knockback=0;const base=q.w.damage;const ammo=s.arms[0].ammo;s.arms=[];for(let i=0;i<100;i++)step(s,.02);assert(Math.abs(e.hp-(1000-base*1.6))<1e-7);assert.equal(ammo,0);assert.equal(s.shots.length,0);});
test('common nerve holds faster hands, emits one coordinated double-damage volley',()=>{const s=gear(run(),{arms:['seed','needle','claws'],organs:['commonNerve']});enemy(s,{x:0,z:2});s.arms[1].cooldown=1;attack(s,0);assert.equal(s.shots.length,0);assert.equal(s.arms[0].ammo,8);s.arms[1].cooldown=0;attack(s,0);assert.equal(s.shots.length,2);assert.equal(s.shots[0].w.damage,weaponStats(s,s.arms[0]).damage*2);assert.equal(s.arms[0].ammo,7);assert.equal(s.arms[1].ammo,0);});
test('conductor emits three targets with electric bonus and plasma, preserves cooldown across removal',()=>{const s=gear(run(),{arms:['arc'],organs:['shield','stabilizer']});for(let i=0;i<4;i++)enemy(s,{x:2+i});s.abilities.learned=['electric.2','plasma'];const hits=[];for(let i=0;i<5;i++)conductorAttack(s,{damage:20,range:10},(e,d,src)=>hits.push([e,d,src]));assert.equal(hits.length,3);assert.equal(hits[0][1],15);assert(hits.every(([e])=>e.burn));const at=s.isaac.conductorAt;unequip(s,'organs',0);equip(s,s.inventory[0].id,0);assert.equal(s.isaac.conductorAt,at);});
test('mire buffs once in overlapping enlarged acid and slime pools, deactivates immediately',()=>{const s=gear(run(),{arms:['acid'],organs:['slime','regen']});const base=stats(s);s.puddles=[{x:3.5,z:0,life:3}];isaacState(s).slimePools=[{x:0,z:0,radius:2,life:3}];assert(inMire(s));assert.equal(stats(s).speed,base.speed*1.25);assert.equal(stats(s).rate,.25);s.organs=[];assert(!inMire(s));assert.equal(stats(s).rate,0);});
test('health trades persist slots and missing health across body swaps and reject lethal trades',()=>{const s=run(),n=node(s,'altar_organs');s.body.tier=2;s.time=180;s.hp=2;s.health.missing=1;assert(takeDeal(s,n.id,'organs'));assert.equal(stats(s).hp,2);assert.equal(s.hp,1);assert.equal(s.organs.length,4);assert.equal(s.arms.length,2);assert(!takeDeal(s,n.id,'organs'));const b=createPart(s,'hunter');s.inventory.push(b);assert(swapBody(s,b.id));assert.equal(s.organs.length,3);assert.equal(s.arms.length,3);assert.equal(stats(s).hp,1);const n2=node(s,'altar_organs');assert(!takeDeal(s,n2.id,'organs'));});
test('fused hand cannot be replaced or left behind during body swap; boss unlock does not remove damage',()=>{const s=run(),n=node(s,'altar'),p=s.arms[0];s.time=180;const damage=weaponStats(s,p).damage;assert(takeDeal(s,n.id,'fuse',p.id));assert.equal(weaponStats(s,p).damage,damage*2);assert(!unequip(s,'arms',0));const replacement=createPart(s,'hammer');s.inventory.push(replacement);assert(!equip(s,replacement.id,0));const body=createPart(s,'hunter');s.inventory.push(body);assert(!swapBody(s,body.id,{arms:[],legs:[],organs:[]}));assert(swapBody(s,body.id));const boss=enemy(s,{kind:'boss',hp:1});hurtEnemy(s,boss,1);assert(!p.bound);assert(p.fused);assert(unequip(s,'arms',0));});
test('outer stomach never consumes ground loot, including legacy marks',()=>{const s=gear(run(),{organs:['outerStomach']});const p=createPart(s,'seed');p.spent=100;s.ground=[{id:1,x:0,z:0,part:p,consume:true},{id:2,x:0,z:0,part:createPart(s,'claws')},{id:3,x:10,z:0,part:createPart(s,'seed'),consume:true}];const before=s.biomass;tickIsaacCombat(s,0,()=>{});assert.deepEqual(s.ground.map(q=>q.id),[1,2,3]);assert.equal(s.biomass,before);});
test('reverse heart responds only to actual heal at full health, preserves cooldown and normal healing',()=>{const s=gear(run(),{organs:['reverseHeart']});const e=enemy(s,{x:2});tickIsaacCombat(s,0,()=>assert.fail());heal(s,stats(s).hp);tickIsaacCombat(s,0,(e,d,source)=>hurtEnemy(s,e,d,0,source));assert.equal(e.hp,1000-weaponStats(s,s.arms[0]).damage*3);heal(s,stats(s).hp);assert.equal(s.isaac.pulses,0);s.time=5;s.hp=1;s.health.missing=1;heal(s,stats(s).hp);assert.equal(s.hp,2);assert.equal(s.isaac.pulses,0);});
test('all nineteen encounters are deterministic and placed on walkable ground across seeds',()=>{for(let seed=1;seed<=20;seed++){const a=createWorldRun(undefined,'survival',seed),b=createWorldRun(undefined,'survival',seed);assert.equal(a.encounters.nodes.length,19);assert.deepEqual(a.encounters,b.encounters);for(const n of a.encounters.nodes)assert(a.world.walkable(n.x,n.z,.7));}});
test('painted adapter also places exactly seven reachable encounters',()=>{const s=createPaintedRun(undefined,'survival',1);assert.equal(s.encounters.nodes.length,7);});
test('reward choice is atomic, seeded, one time, gives slab biomass and unlocks selected key',()=>{const s=run(),n=node(s,'slab');const before=[...n.rewards];openSecret(s,n);assert(claimEncounter(s,n.id,0));assert.equal(s.biomass,30);assert.equal(s.ground[0].part.key,'slime');assert(s.profile.unlocked.includes('slime'));assert(!claimEncounter(s,n.id,1));assert.deepEqual(n.rewards,before);});
test('acid secret opens on projectile impact, incompatible hands never open it',()=>{const s=gear(run(),{arms:['seed']}),n=node(s,'membrane');n.x=5;attack(s,0);assert.equal(n.state,'ready');gear(s,{arms:['acid']});attack(s,0);assert.equal(n.state,'ready');s.arms=[];for(let i=0;i<20;i++)step(s,.05);assert.equal(n.state,'reward');});
test('challenge gates reject early start, bosses, a second challenge and pending choices',()=>{const s=run(),n=node(s,'hunt');assert(!challengeAllowed(s,n));s.time=300;const e=enemy(s,{kind:'boss'});assert(!challengeAllowed(s,n));e.hp=0;s.pending=1;assert(!challengeAllowed(s,n));s.pending=0;assert(beginEncounter(s,n.id));assert(!beginEncounter(s,n.id));});
test('challenge freezes run and mission clocks, waves and XP pause freezes every clock',()=>{const s=gear(run(),{arms:[],organs:['shield']}),n=node(s,'infection');s.time=300;assert(beginEncounter(s,n.id));const main=s.time;s.health.invulnerableUntil=combatTime(s)+.3;step(s,.5);assert.equal(s.time,main);assert.equal(combatTime(s),main+.5);assert.equal(s.enemies.filter(e=>e.challengeId===n.id).length,3);assert.equal(n.progress,.5);assert.equal(receiveHit(s,stats(s)),'hurt');s.pending=1;const before=combatTime(s);step(s,1);assert.equal(combatTime(s),before);assert.equal(n.progress,.5);});
test('infection disables healing inside, accumulates only inside and completes once',()=>{const s=run(),n=node(s,'infection');s.time=300;beginEncounter(s,n.id);s.hp=2;s.health.missing=1;heal(s,stats(s).hp);assert.equal(s.hp,2);s.player.x=n.x+n.radius+2;heal(s,stats(s).hp);assert.equal(s.hp,2);tickChallenge(s,10);assert.equal(n.progress,0);s.player.x=0;tickChallenge(s,30);assert.equal(n.state,'reward');assert.equal(s.encounters.active,null);});
test('sealed area contains player until both timer and enemies complete; hunt failure leaves elite alive',()=>{const s=gear(run(),{arms:[]}),n=node(s,'sealed');s.time=300;assert(beginEncounter(s,n.id));s.player.x=6.2;step(s,.5,{x:1,z:0});assert(s.player.x<=6.3);tickChallenge(s,45);assert.equal(n.state,'active');for(const e of s.enemies)e.hp=0;tickChallenge(s,0);assert.equal(n.state,'reward');s.player={x:0,z:0};const h=node(s,'hunt');beginEncounter(s,h.id);tickChallenge(s,60);assert.equal(h.state,'failed');assert(s.enemies.some(e=>e.hp>0&&e.challengeId===h.id));});
test('discovered challenge adapts a reward to incomplete family once without UI rerolls',()=>{const s=gear(run(),{arms:['rocket'],organs:[]}),n=node(s,'hunt');s.time=300;discoverEncounters(s);assert(n.rewards.includes('fangs'));const rewards=[...n.rewards];s.arms=[createPart(s,'acid')];discoverEncounters(s);assert.deepEqual(n.rewards,rewards);});
test('rare pool remains available in fresh profile and excludes rare organs from ordinary pool',()=>{const s=run();s.time=480;s.rng=()=>.9999;assert.equal(randomLoot(s).rarity,'relic');s.rng=()=>.5;s.profile.unlocked.push('commonNerve');for(let i=0;i<10;i++)assert.notEqual(randomLoot(s).key,'commonNerve');});
test('secondary populations are bounded even under a mass death burst',()=>{const s=gear(run(),{arms:['rocket','fangs'],organs:['parasite','digestion','slime']});for(let i=0;i<300;i++){const e={x:1,z:0,kind:'normal',slimeUntil:3,clutch:{until:6,damage:20}};isaacDeath(s,e,'direct');}assert.equal(s.isaac.larvae.length,120);assert.equal(s.isaac.slimePools.length,80);tickIsaacCombat(s,6,()=>{});assert.equal(s.isaac.larvae.length,0);assert.equal(s.isaac.slimePools.length,0);});
test('multiple mutations can coexist; duplicate organs are atomically rejected',()=>{const s=gear(run(),{arms:['rocket','fangs','arc','acid'],organs:['digestion','slime','regen','shield','stabilizer']});assert.equal(mutationView(s).filter(f=>f.active).length,3);const p=createPart(s,'slime');s.inventory.push(p);assert(!equip(s,p.id,0));assert.equal(s.organs[0].key,'digestion');});
test('health deal price cannot be erased by body comparison and replacing a bound slot is rejected there too',()=>{const s=run(),n=node(s,'altar_organs');s.time=180;takeDeal(s,n.id,'organs');const c=cloneForComparison(s);assert.equal(stats(c).hp,1);assert.equal(c.organs.length,3);assert.equal(s.isaac.deals.hpCost,1);});
test('health recovery, burn, echo and shields continue on combat time while mission progress is paused',()=>{const s=gear(run(),{arms:['seed'],organs:['shield','regen']});s.mode='garden';s.mission={id:'garden',name:'test',nodes:[],activated:3,last:{x:50,z:50},defense:12,targetHp:80,duration:600};const n=node(s,'infection');s.time=300;beginEncounter(s,n.id);s.player.x=n.x+n.radius+2;s.hp=1;s.health.missing=1;s.health.regenAt=301;s.organs[0].shieldReadyAt=301;const e=enemy(s,{x:s.player.x+1});e.burn={dps:10,until:301};s.arms[0].cooldown=100;s.abilities.echoes.push({partId:s.arms[0].id,at:300.1});step(s,1);assert.equal(s.time,300);assert.equal(s.mission.defense,12);assert.equal(s.hp,2);assert.equal(s.organs[0].shieldCharge,1);assert.equal(s.abilities.echoes.length,0);assert(e.hp<1000);});
test('electrical ability and conductor lightning can wake a secret without an arc hand',()=>{const s=gear(run(),{arms:['seed'],organs:[]}),n=node(s,'nursery');n.x=4;s.abilities.learned=['electric.0'];enemy(s,{x:3});for(let i=0;i<5;i++){s.arms[0].cooldown=0;attack(s,0);}assert.equal(n.state,'reward');});
test('outer stomach exposes loot before the three-metre auto-pickup boundary',async()=>{const {nearbyLootRadius}=await import('../src/systems/mutations.js');const s=gear(run(),{organs:['outerStomach']});assert.equal(nearbyLootRadius(s),10);const q={id:999,x:5,z:0,part:createPart(s,'seed')};s.ground.push(q);q.consume=true;tickIsaacCombat(s,.05,()=>{});assert(s.ground.includes(q));s.player.x=3;step(s,.05);assert(!s.ground.includes(q));assert(s.inventory.some(p=>p.id===q.part.id));assert.equal(s.biomass,0);s.organs=[];assert.equal(nearbyLootRadius(s),3);});

test('all secret tools open their matching objects and each reward is claimed once',()=>{
 for(const [type,key] of [['membrane','acid'],['slab','hammer'],['slab','drill'],['nursery','arc']]){
  const s=gear(run(),{arms:[key]}),n=node(s,type);n.x=1.5;attack(s,0);
  if(key==='acid'){s.arms=[];for(let i=0;i<20;i++)step(s,.05);}
  assert.equal(n.state,'reward',type+' / '+key);assert(claimEncounter(s,n.id,0));assert(!claimEncounter(s,n.id,0));
 }
});
