import test from 'node:test';
import assert from 'node:assert/strict';
import {createRun,step,attack,hurtEnemy,beginEncounter,randomLoot} from '../src/game.js';
import {createWorldRun} from '../src/world-run.js';
import {createPaintedRun} from '../src/painterly-stage.js';
import {createPart,equip,unequip,swapBody,stats,weaponStats,digest,upgrade,upgradeOptions,newProfile} from '../src/assembly.js';
import {mutationView,isaacState,activeMutation,combatTime,hasOrgan,inMire} from '../src/systems/mutations.js';
import {prepareIsaacAttack,isaacHit,isaacDeath,conductorAttack,tickIsaacCombat,slimePace} from '../src/systems/isaac-combat.js';
import {heal,tickHealth,receiveHit} from '../src/systems/health.js';
import {prepareEncounters,discoverEncounters,takeDeal,claimEncounter,openSecret,challengeAllowed,tickChallenge,ENCOUNTERS} from '../src/systems/encounters.js';
import {cloneForComparison,unlockCondition} from '../src/ui/adapters.js';
import {compatibility,mutationWarning} from '../src/ui/isaac-ui.js';
function run(){const s=createRun(undefined,'survival',19);s.world={walkable:()=>true,lineClear:()=>true,heightAt:()=>0,chunk:()=>({cx:0,cz:0,lair:{x:999,z:999}})};s.encounters={nodes:[],active:null};s.rng=()=>.99;s.nextElite=s.nextBoss=1e9;return s;}
function gear(s,{arms=['seed'],organs=[],legs=['universal','universal']}={}){s.arms=arms.map(k=>createPart(s,k));s.organs=organs.map(k=>createPart(s,k));s.legs=legs.map(k=>createPart(s,k));return s;}
function enemy(s,{x=5,z=0,hp=1000,kind='normal',...rest}={}){const e={id:++s.entityId,x,z,hp,maxHp:hp,kind,armor:0,radius:1,speed:0,contact:99,damage:1,born:0,xp:0,...rest};s.enemies.push(e);return e;}
function node(s,type){if(type==='altar'){s.level=20;s.time=1200;}const n={id:'encounter-'+type,type,x:0,y:0,z:0,radius:ENCOUNTERS[type].radius||1,unlockLevel:type==='altar'?20:0,state:'ready',rewards:['slime','parasite','regen'],deals:['organs','fuse'],discovered:true,claimed:false};s.encounters.nodes.push(n);return n;}
test('distinct equipped family types activate together, inventory and duplicates do not count',()=>{const s=gear(run(),{arms:['acid'],organs:['slime','regen'],legs:['plated','plated']});assert(activeMutation(s,'mire'));s.inventory.push(createPart(s,'rocket'));assert(!activeMutation(s,'hive'));s.organs=[];assert.equal(mutationView(s).find(f=>f.id==='mire').count,2);});
test('switching equipment disables mutation without resetting combat counters',()=>{const s=gear(run(),{arms:['rocket','fangs'],organs:['digestion']});isaacState(s).hiveKills=4;assert(activeMutation(s,'hive'));const copy=cloneForComparison(s);assert(unequip(copy,'organs',0));assert.match(mutationWarning(s,copy),/Улей/);assert(unequip(s,'organs',0));assert(!activeMutation(s,'hive'));assert(equip(s,s.inventory[0].id,0));assert.equal(s.isaac.hiveKills,4);assert(activeMutation(s,'hive'));});
test('new behavior organs have only meaningful upgrades and describe compatible hands',()=>{const s=gear(run(),{arms:['seed','acid']});assert.deepEqual(upgradeOptions(createPart(s,'reverseHeart')),['heartDamage']);assert.deepEqual(upgradeOptions(createPart(s,'commonNerve')),['commonVolley']);assert.deepEqual(upgradeOptions(createPart(s,'slime')),['slimeSlow']);assert.deepEqual(upgradeOptions(createPart(s,'parasite')),['larvaDamage']);assert.match(compatibility(s,createPart(s,'returnNerve')),/Сеялка/);assert.match(unlockCondition('reverseHeart'),/Эпическая/);});
test('all-hand organs do not render compatibility lists',()=>{const s=gear(run(),{arms:['claws','seed']});for(const key of ['slime','parasite'])assert.equal(compatibility(s,createPart(s,key)),'');});
test('parasite no longer infects from hand attacks or repeats',()=>{
 const s=gear(run(),{arms:['seed'],organs:['parasite']}),p=s.arms[0],e=enemy(s);
 for(let i=0;i<6;i++){const w=prepareIsaacAttack(s,p,weaponStats(s,p));assert.equal(w.isaac.parasite,undefined);isaacHit(s,e,100,w);}
 assert.equal(e.clutch,undefined);
});
test('death leaves slime but neither old infection nor larva kills reproduce',()=>{
 const s=gear(run(),{organs:['slime','parasite']}),e=enemy(s,{hp:1});
 isaacHit(s,e,100,{isaac:{slime:true,parasite:true}});e.clutch={until:100,damage:100};hurtEnemy(s,e,1);
 assert.equal(s.isaac.larvae.length,0);assert.equal(s.isaac.slimePools.length,1);
 s.enemies=[];for(let i=0;i<40;i++)tickIsaacCombat(s,.05,()=>{});assert.equal(s.isaac.larvae.length,2);
 const target=enemy(s,{x:0,hp:1});isaacDeath(s,target,'larva');assert.equal(s.isaac.larvae.length,2);
});
test('slime pools slow every enemy class equally without damaging, infecting or extending corpse slime',()=>{const s=gear(run()),e=enemy(s);isaacState(s).slimePools.push({x:5,z:0,radius:2,life:3});assert.equal(slimePace(s,e),.9);assert.equal(slimePace(s,{...e,kind:'boss'}),.9);assert.equal(slimePace(s,{...e,kind:'final'}),.9);tickIsaacCombat(s,1,()=>assert.fail('no damage'));assert.equal(e.hp,1000);assert.equal(e.slimeUntil,undefined);});
test('slime slowdown scales five points by rank and two points per upgrade, then snapshots on hit',()=>{
 for(const [tier,slow] of [[1,.1],[2,.15],[3,.2],[4,.25],[5,.3]])for(const upgrades of [0,1,10]){
  const s=gear(run(),{organs:['slime']});s.organs[0].tier=tier;for(let i=0;i<upgrades;i++)assert(upgrade(s,s.organs[0].id,'slimeSlow'));
  const w=prepareIsaacAttack(s,s.arms[0],{});s.organs=[];const regular=enemy(s),leader=enemy(s,{kind:'boss'});isaacHit(s,regular,1,w);isaacHit(s,leader,1,w);
  assert.ok(Math.abs(slimePace(s,regular)-(1-slow-upgrades*.02))<1e-9);assert.ok(Math.abs(slimePace(s,leader)-(1-slow-upgrades*.02))<1e-9);
 }
});
test('expired clutch never spawns, persistent shots retain organ snapshots',()=>{const s=gear(run(),{organs:['parasite','slime']});const e=enemy(s);const w=prepareIsaacAttack(s,s.arms[0],weaponStats(s,s.arms[0]));s.organs=[];isaacHit(s,e,5,w);assert.equal(e.slimeUntil,3);e.clutch={until:1,damage:40};s.time=2;isaacDeath(s,e,'direct');assert.equal(s.isaac.larvae.length,0);});
test('timed parasite larvae scale by rank and upgrades and snapshot chassis power',()=>{
 for(const [tier,base] of [[1,6],[2,9],[3,12],[4,15],[5,18]])for(const boost of [1,1.3])for(const upgrades of [0,1,10]){
  const s=gear(run(),{organs:['parasite']});s.organs[0].tier=tier;
  if(boost>1){s.body=createPart(s,'bastion');isaacState(s).deals.organs=1;s.organs.push(createPart(s,'stabilizer'),createPart(s,'regen'),createPart(s,'digestion'));}
  for(let i=0;i<upgrades;i++)assert(upgrade(s,s.organs[0].id,'larvaDamage'));
  for(let i=0;i<40;i++)tickIsaacCombat(s,.05,()=>{});s.organs=[];
  assert.equal(s.isaac.larvae.length,2);for(const l of s.isaac.larvae)assert.ok(Math.abs(l.damage-(base+upgrades*2.4)*boost)<1e-9);
 }
});
test('return damage scales from 10 to 50 percent by organ rank and snapshots chassis power without refunding ammo',()=>{
 for(const key of ['seed','needle'])for(const [tier,ratio] of [[1,.1],[2,.2],[3,.3],[4,.4],[5,.5]])for(const boost of [1,1.3])for(const upgrades of [0,1,10]){
  const s=gear(run(),{arms:[key],organs:['returnNerve']});s.organs[0].tier=tier;if(boost>1){s.body=createPart(s,'bastion');isaacState(s).deals.organs=1;s.organs.push(createPart(s,'stabilizer'),createPart(s,'regen'),createPart(s,'digestion'));}
  for(let i=0;i<upgrades;i++)assert(upgrade(s,s.organs[0].id,'returnDamage'));
  s.arms[0].ammo=1;const e=enemy(s);attack(s,0);const q=s.shots[0];q.w.knockback=0;const base=q.w.damage,ammo=s.arms[0].ammo;
  s.arms=[];s.organs=[];
  for(let i=0;i<160;i++)step(s,.02);
  assert(Math.abs(e.hp-(1000-base*(1+(ratio+upgrades*.03)*boost)))<1e-7,`${key} rank ${tier} boost ${boost}`);assert.equal(ammo,0);assert.equal(s.shots.length,0);
 }
});
test('common nerve holds faster hands while rank and upgrades improve its coordinated volley',()=>{const s=gear(run(),{arms:['seed','needle','claws'],organs:['commonNerve']});enemy(s,{x:0,z:2});s.arms[1].cooldown=1;attack(s,0);assert.equal(s.shots.length,0);assert.equal(s.arms[0].ammo,8);s.arms[1].cooldown=0;attack(s,0);assert.equal(s.shots.length,2);assert.equal(s.shots[0].w.damage,weaponStats(s,s.arms[0]).damage*1.5);assert.equal(s.arms[0].ammo,7);assert.equal(s.arms[1].ammo,0);assert(upgrade(s,s.organs[0].id,'commonVolley'));s.organs[0].tier=5;s.arms[0].cooldown=s.arms[1].cooldown=0;s.arms[1].ammo=1;s.arms[1].reloadRemaining=0;const before=s.shots.length;attack(s,0);assert.equal(s.shots[before].w.damage,weaponStats(s,s.arms[0]).damage*2);});
test('conductor emits three targets with electric bonus and plasma, preserves cooldown across removal',()=>{const s=gear(run(),{arms:['arc'],organs:['shield','stabilizer']});for(let i=0;i<4;i++)enemy(s,{x:2+i});s.abilities.learned=['electric.2','plasma'];const hits=[];for(let i=0;i<5;i++)conductorAttack(s,{damage:20,range:10},(e,d,src)=>hits.push([e,d,src]));assert.equal(hits.length,3);assert.equal(hits[0][1],15);assert(hits.every(([e])=>e.burn));const at=s.isaac.conductorAt;unequip(s,'organs',0);equip(s,s.inventory[0].id,0);assert.equal(s.isaac.conductorAt,at);});
test('mire buffs once in overlapping enlarged acid and slime pools, deactivates immediately',()=>{const s=gear(run(),{arms:['acid'],organs:['slime','regen']});const base=stats(s);s.puddles=[{x:3.5,z:0,life:3}];isaacState(s).slimePools=[{x:0,z:0,radius:2,life:3}];assert(inMire(s));assert.equal(stats(s).speed,base.speed*1.25);assert.equal(stats(s).rate,.25);s.organs=[];assert(!inMire(s));assert.equal(stats(s).rate,0);});
test('health trades persist slots and missing health across body swaps and reject lethal trades',()=>{const s=run(),n=node(s,'altar_organs');s.body.tier=2;s.time=180;s.hp=2;s.health.missing=1;assert(takeDeal(s,n.id,'organs'));assert.equal(stats(s).hp,2);assert.equal(s.hp,1);assert.equal(s.organs.length,4);assert.equal(s.arms.length,2);assert(!takeDeal(s,n.id,'organs'));const b=createPart(s,'hunter');s.inventory.push(b);assert(swapBody(s,b.id));assert.equal(s.organs.length,3);assert.equal(s.arms.length,3);assert.equal(stats(s).hp,1);const n2=node(s,'altar_organs');assert(!takeDeal(s,n2.id,'organs'));});
test('fused hand cannot be replaced or left behind during body swap and stays bound after a boss',()=>{const s=run(),n=node(s,'altar'),p=s.arms[0];s.time=180;const damage=weaponStats(s,p).damage;assert(takeDeal(s,n.id,'fuse',p.id));assert.equal(weaponStats(s,p).damage,damage*2);assert(!unequip(s,'arms',0));const replacement=createPart(s,'hammer');s.inventory.push(replacement);assert(!equip(s,replacement.id,0));const body=createPart(s,'hunter');s.inventory.push(body);assert(!swapBody(s,body.id,{arms:[],legs:[],organs:[]}));assert(swapBody(s,body.id));const boss=enemy(s,{kind:'boss',hp:1});hurtEnemy(s,boss,1);assert(p.bound);assert(p.fused);assert(!unequip(s,'arms',0));});
test('reverse heart responds only to actual heal while rank and upgrades improve its impulse',()=>{const s=gear(run(),{organs:['reverseHeart']});const e=enemy(s,{x:2}),base=weaponStats(s,s.arms[0]).damage;tickIsaacCombat(s,0,()=>assert.fail());heal(s,stats(s).hp);tickIsaacCombat(s,0,(e,d,source)=>hurtEnemy(s,e,d,0,source));assert.equal(e.hp,1000-base*2);heal(s,stats(s).hp);assert.equal(s.isaac.pulses,0);s.time=5;assert(upgrade(s,s.organs[0].id,'heartDamage'));s.organs[0].tier=5;heal(s,stats(s).hp);tickIsaacCombat(s,0,(e,d,source)=>hurtEnemy(s,e,d,0,source));assert.equal(e.hp,1000-base*5);s.hp=1;s.health.missing=1;heal(s,stats(s).hp);assert.equal(s.hp,2);assert.equal(s.isaac.pulses,0);});
test('all encounters are deterministic and placed on walkable ground across seeds',()=>{for(let seed=1;seed<=20;seed++){const a=createWorldRun(undefined,'survival',seed),b=createWorldRun(undefined,'survival',seed);assert.ok([26,27].includes(a.encounters.nodes.length));assert.deepEqual(a.encounters,b.encounters);for(const n of a.encounters.nodes)assert(a.world.walkable(n.x,n.z,.7));}});
test('painted adapter also places exactly seven reachable encounters with the shared sealed radius',()=>{const s=createPaintedRun(undefined,'survival',1);assert.equal(s.encounters.nodes.length,7);assert.equal(s.encounters.nodes.find(n=>n.type==='sealed').radius,11);});
test('reward choice is atomic, seeded, one time, gives slab biomass and unlocks selected key',()=>{const s=run(),n=node(s,'slab');const before=[...n.rewards];openSecret(s,n);assert(claimEncounter(s,n.id,0));assert.equal(s.biomass,30);assert.equal(s.ground[0].part.key,'slime');assert(s.profile.unlocked.includes('slime'));assert(!claimEncounter(s,n.id,1));assert.deepEqual(n.rewards,before);});
test('acid secret opens on projectile impact, incompatible hands never open it',()=>{const s=gear(run(),{arms:['seed']}),n=node(s,'membrane');n.x=5;attack(s,0);assert.equal(n.state,'ready');gear(s,{arms:['acid']});attack(s,0);assert.equal(n.state,'ready');s.arms=[];for(let i=0;i<20;i++)step(s,.05);assert.equal(n.state,'reward');});
test('challenge gates reject early start, bosses, a second challenge and pending choices',()=>{const s=run(),n=node(s,'hunt');assert(!challengeAllowed(s,n));s.time=300;const e=enemy(s,{kind:'boss'});assert(!challengeAllowed(s,n));e.hp=0;s.pending=1;assert(!challengeAllowed(s,n));s.pending=0;assert(beginEncounter(s,n.id));assert(!beginEncounter(s,n.id));});
test('challenge freezes run and mission clocks, waves and XP pause freezes every clock',()=>{const s=gear(run(),{arms:[],organs:['shield']}),n=node(s,'infection');s.time=300;assert(beginEncounter(s,n.id));const main=s.time;s.health.invulnerableUntil=combatTime(s)+.3;step(s,.5);assert.equal(s.time,main);assert.equal(combatTime(s),main+.5);assert.equal(s.enemies.filter(e=>e.challengeId===n.id).length,3);assert.equal(n.progress,.5);assert.equal(receiveHit(s,stats(s)),'armor');assert.equal(receiveHit(s,stats(s)),'hurt');s.pending=1;const before=combatTime(s);step(s,1);assert.equal(combatTime(s),before);assert.equal(n.progress,.5);});
test('infection disables healing inside, accumulates only inside and completes once',()=>{const s=run(),n=node(s,'infection');s.time=300;beginEncounter(s,n.id);s.hp=2;s.health.missing=1;heal(s,stats(s).hp);assert.equal(s.hp,2);s.player.x=n.x+n.radius+2;heal(s,stats(s).hp);assert.equal(s.hp,2);tickChallenge(s,10);assert.equal(n.progress,0);s.player.x=0;tickChallenge(s,30);assert.equal(n.state,'reward');assert.equal(s.encounters.active,null);});
test('sealed area contains player until both timer and enemies complete; hunt failure leaves elite alive',()=>{const s=gear(run(),{arms:[]}),n=node(s,'sealed');s.time=300;assert(beginEncounter(s,n.id));s.player.x=n.radius-.8;step(s,.5,{x:1,z:0});assert(s.player.x<=n.radius-.7);tickChallenge(s,45);assert.equal(n.state,'active');for(const e of s.enemies)e.hp=0;tickChallenge(s,0);assert.equal(n.state,'reward');s.player={x:0,z:0};const h=node(s,'hunt');beginEncounter(s,h.id);tickChallenge(s,60);assert.equal(h.state,'failed');assert(s.enemies.some(e=>e.hp>0&&e.challengeId===h.id));});
test('discovered challenge adapts a reward to incomplete family once without UI rerolls',()=>{const s=gear(run(),{arms:['rocket'],organs:[]}),n=node(s,'hunt');s.time=300;discoverEncounters(s);assert(n.rewards.includes('fangs'));const rewards=[...n.rewards];s.arms=[createPart(s,'acid')];discoverEncounters(s);assert.deepEqual(n.rewards,rewards);});
test('rare pool remains available in fresh profile and excludes rare organs from ordinary pool',()=>{const s=run();s.time=480;s.rng=()=>.9999;assert.equal(randomLoot(s).rarity,'relic');s.rng=()=>.5;s.profile.unlocked.push('commonNerve');for(let i=0;i<10;i++)assert.notEqual(randomLoot(s).key,'commonNerve');});
test('secondary pools are bounded and retired death infections do not spawn larvae',()=>{const s=gear(run(),{arms:['rocket','fangs'],organs:['parasite','digestion','slime']});for(let i=0;i<300;i++){const e={x:1,z:0,kind:'normal',slimeUntil:3,clutch:{until:6,damage:20}};isaacDeath(s,e,'direct');}assert.equal(s.isaac.larvae.length,0);assert.equal(s.isaac.slimePools.length,80);tickIsaacCombat(s,6,()=>{});assert.equal(s.isaac.larvae.length,0);assert.equal(s.isaac.slimePools.length,0);});
test('multiple mutations coexist and replacing an organ with a duplicate updates family membership',()=>{const s=gear(run(),{arms:['rocket','fangs','arc','acid'],organs:['digestion','slime','regen','shield','stabilizer']});assert.equal(mutationView(s).filter(f=>f.active).length,3);const previous=s.organs[0],p=createPart(s,'slime');s.inventory.push(p);assert(equip(s,p.id,0));assert.equal(s.organs[0],p);assert(s.inventory.includes(previous));assert.equal(s.organs.filter(q=>q?.key==='slime').length,2);assert(!activeMutation(s,'hive'));assert.equal(mutationView(s).filter(f=>f.active).length,2);});
test('health deal price cannot be erased by body comparison and replacing a bound slot is rejected there too',()=>{const s=run(),n=node(s,'altar_organs');s.time=180;takeDeal(s,n.id,'organs');const c=cloneForComparison(s);assert.equal(stats(c).hp,1);assert.equal(c.organs.length,3);assert.equal(s.isaac.deals.hpCost,1);});
test('health recovery, burn, echo and shields continue on combat time while mission progress is paused',()=>{const s=gear(run(),{arms:['seed'],organs:['shield','regen']});s.mode='garden';s.mission={id:'garden',name:'test',nodes:[],activated:3,last:{x:50,z:50},defense:12,targetHp:80,duration:600};const n=node(s,'infection');s.time=300;beginEncounter(s,n.id);s.player.x=n.x+n.radius+2;s.hp=1;s.health.missing=1;s.health.regenAt=301;s.organs[0].shieldReadyAt=301;const e=enemy(s,{x:s.player.x+1});e.burn={dps:10,until:301};s.arms[0].cooldown=100;s.abilities.echoes.push({partId:s.arms[0].id,at:300.1});step(s,1);assert.equal(s.time,300);assert.equal(s.mission.defense,12);assert.equal(s.hp,2);assert.equal(s.organs[0].shieldCharge,1);assert.equal(s.abilities.echoes.length,0);assert(e.hp<1000);});
test('electrical ability and conductor lightning can wake a secret without an arc hand',()=>{const s=gear(run(),{arms:['seed'],organs:[]}),n=node(s,'nursery');n.x=4;s.abilities.learned=['electric.0'];enemy(s,{x:3});for(let i=0;i<5;i++){s.arms[0].cooldown=0;attack(s,0);}assert.equal(n.state,'reward');});

test('all secret tools open their matching objects and each reward is claimed once',()=>{
 for(const [type,key] of [['membrane','acid'],['slab','hammer'],['slab','drill'],['nursery','arc']]){
  const s=gear(run(),{arms:[key]}),n=node(s,type);n.x=1.5;attack(s,0);
  if(key==='acid'){s.arms=[];for(let i=0;i<20;i++)step(s,.05);}
  assert.equal(n.state,'reward',type+' / '+key);assert(claimEncounter(s,n.id,0));assert(!claimEncounter(s,n.id,0));
 }
});
