import test from 'node:test';import assert from 'node:assert/strict';
import {createRun,spawnEnemy,hurtEnemy,applyStartingLoadout,rerollReward,addXP,attack} from '../src/game.js';
import {newProfile,readProfile,createPart,stats,weaponStats} from '../src/assembly.js';
import {meta,validLoadout,starterAllowed,startOverrun,tickOverrun,awardMeta,recordVictory} from '../src/systems/meta-progression.js';
import {tickExtraParts,reactorKill,pullHarpoon} from '../src/systems/extra-parts.js';
import {receiveHit} from '../src/systems/health.js';
const run=()=>{const s=createRun(undefined,'survival',42);s.world={walkable:()=>true};return s;};
test('legacy saves migrate and malformed profile currency cannot grant tokens',()=>{const old=newProfile();delete old.meta;const p=readProfile({getItem:()=>JSON.stringify(old)});assert.equal(meta(p).rerolls,0);old.meta={overruns:-5,rerolls:Infinity,wins:'3'};assert.equal(readProfile({getItem:()=>JSON.stringify(old)}).meta.rerolls,0);});
test('starter gates validate tampered selection; 3rd success grants optional organ',()=>{const p=newProfile();assert.deepEqual(validLoadout(p,{body:'bastion',arm:'harpoon',organ:'stabilizer'}),{body:'wanderer',arm:'claws',organ:null});for(let i=0;i<=3;i++){meta(p).overruns=i;assert.equal(starterAllowed(p,'hunter'),i>=1);assert.equal(starterAllowed(p,'bastion'),i>=2);assert.equal(starterAllowed(p,'stabilizer'),i>=3);}const s=run();s.profile=p;applyStartingLoadout(s,{body:'bastion',arm:'harpoon',organ:'stabilizer'});assert.equal(s.arms[0].key,'harpoon');assert.equal(s.legs.length,4);assert.equal(s.organs[0].key,'stabilizer');assert.equal(s.biomass,0);assert.ok(stats(s).speed>0);});
test('overrun requires final victory, elapsed time AND both elite kills; rewards exactly once',()=>{const s=run(),spawn=(...a)=>spawnEnemy(s,...a);assert.equal(startOverrun(s,spawn),false);s.finalDefeated=s.won=true;recordVictory(s);recordVictory(s);assert.equal(meta(s.profile).wins,1);assert.ok(startOverrun(s,spawn));tickOverrun(s,31,spawn,createPart);assert.equal(meta(s.profile).rerolls,0);for(const id of s.overrun.guards)s.enemies.find(e=>e.id===id).hp=0;tickOverrun(s,.01,spawn,createPart);assert.equal(s.overrun.state,'complete');assert.equal(meta(s.profile).rerolls,2);assert.equal(s.continued,false);assert.ok(s.inventory.some(p=>p.key==='harpoon'));assert.equal(startOverrun(s,spawn),false);tickOverrun(s,100,spawn,createPart);assert.equal(meta(s.profile).rerolls,2);});
test('failed overrun retains win but gives no tokens; partial spawn does not start challenge',()=>{const s=run();s.won=s.finalDefeated=true;recordVictory(s);let n=0;assert.equal(startOverrun(s,(...a)=>++n===1?spawnEnemy(s,...a):null),false);assert.equal(s.enemies.length,0);assert.ok(startOverrun(s,(...a)=>spawnEnemy(s,...a)));s.dead=true;tickOverrun(s,40,()=>null,createPart);assert.equal(s.overrun.state,'failed');assert.equal(meta(s.profile).wins,1);assert.equal(meta(s.profile).rerolls,0);});
test('two rerolls persist and are consumed only for an active choice without losing level',()=>{const s=run();meta(s.profile).rerolls=2;assert.equal(rerollReward(s),false);addXP(s,20);const old=s.choices.map(c=>c.id),pending=s.pending;assert.ok(rerollReward(s));assert.equal(s.pending,pending);assert.notDeepEqual(s.choices.map(c=>c.id),old);assert.equal(meta(s.profile).rerolls,1);const p=readProfile({getItem:()=>JSON.stringify(s.profile)});assert.equal(meta(p).rerolls,1);assert.ok(rerollReward(s));assert.equal(rerollReward(s),false);});
test('achievement rewards are awarded once and real biome types drive exploration goal',()=>{const s=run();s.elites=5;awardMeta(s,createPart);awardMeta(s,createPart);assert.equal(s.inventory.filter(p=>p.key==='mirrorGland').length,1);s.world.tiles=['gardens','forest','city','scrapyard'].map((biome,i)=>({id:'tile-'+i,biome,kind:'arena'}));s.exploration={visited:new Set(s.world.tiles.map(t=>t.id))};s.encounters={nodes:[{type:'altar',state:'complete'},{type:'infection',state:'complete'}]};awardMeta(s,createPart);assert.ok(s.profile.unlocked.includes('spring'));});
test('mirror responds to shield hits once per 2s, does not block damage or recursively trigger',()=>{const s=run();s.organs=[createPart(s,'mirrorGland'),createPart(s,'shield')];s.organs[1].shieldCharge=1;const e=spawnEnemy(s,'normal',{x:3,z:0});e.hp=e.maxHp=1000;const hits=[];tickExtraParts(s,0,(...a)=>hits.push(a));assert.equal(receiveHit(s,stats(s)),'shield');tickExtraParts(s,.1,(...a)=>hits.push(a));assert.equal(hits.length,1);s.time=1;receiveHit(s,stats(s));tickExtraParts(s,.1,(...a)=>hits.push(a));assert.equal(hits.length,1);assert.equal(s.hp,1);s.time=2;s.organs[1].shieldCharge=1;receiveHit(s,stats(s));tickExtraParts(s,.1,(...a)=>hits.push(a));assert.equal(hits.length,2);tickExtraParts(s,.1,(...a)=>hits.push(a));assert.equal(hits.length,2);});
test('reactor opens 6s attack window then cooldown; normal chassis gets no bonus',()=>{const s=run();s.body=createPart(s,'reactor');const normal=weaponStats(s,s.arms[0]).interval;for(let i=0;i<14;i++)reactorKill(s);assert.equal(weaponStats(s,s.arms[0]).interval,normal);reactorKill(s);assert.ok(weaponStats(s,s.arms[0]).interval<normal);s.time=6;assert.equal(weaponStats(s,s.arms[0]).interval,normal);for(let i=0;i<20;i++)reactorKill(s);assert.equal(s.extraParts.reactorCharge,0);s.time=21;reactorKill(s);assert.equal(s.extraParts.reactorCharge,1);});
test('spring needs sustained movement and sharp turn, does not stack with two legs',()=>{const s=run();s.legs=[createPart(s,'spring'),createPart(s,'spring')];const base=stats(s).speed;s.motion={x:1,z:0};for(let i=0;i<30;i++){s.time+=.1;tickExtraParts(s,.1,()=>{});}s.motion={x:0,z:1};tickExtraParts(s,.1,()=>{});assert.ok(Math.abs(stats(s).speed/base-1.35)<1e-8);s.time+=1.1;assert.equal(stats(s).speed,base);});
test('harpoon pulls only ordinary enemies and obeys obstacle movement',()=>{const s=run(),e=spawnEnemy(s,'normal',{x:8,z:0});pullHarpoon(s,e);assert.ok(e.x<8);const boss=spawnEnemy(s,'boss',{x:8,z:0});pullHarpoon(s,boss);assert.equal(boss.x,8);});
test('reroll prioritizes unseen eligible abilities and boss options remain distinct',()=>{const s=run();meta(s.profile).rerolls=3;addXP(s,20);const old=s.choices.map(c=>c.id);rerollReward(s);assert.ok(s.choices.filter(c=>!old.includes(c.id)).length>=3);s.pending=0;const boss=spawnEnemy(s,'boss',{x:3,z:0});hurtEnemy(s,boss,10000);const rarity=s.bossRewards[0].rarity;assert.ok(rerollReward(s));assert.equal(s.bossRewards.length,1);assert.equal(s.bossRewards[0].rarity,rarity);assert.equal(new Set(s.bossRewards[0].options.map(p=>p.key)).size,3);});
test('reactor integrates with actual kill resolution and stops charging during cooldown',()=>{const s=run();s.body=createPart(s,'reactor');for(let i=0;i<15;i++)hurtEnemy(s,spawnEnemy(s,'normal',{x:2,z:0}),1000);assert.equal(s.kills,15);assert.equal(s.extraParts.reactorUntil,6);assert.ok(stats(s).rate>=.3);});

test('three starter organs share the unlock gate and equip exactly one selected organ',()=>{
 for(const key of ['stabilizer','regen','shield']){
  const s=run();meta(s.profile).overruns=2;
  assert.equal(validLoadout(s.profile,{organ:key}).organ,null);
  meta(s.profile).overruns=3;
  const choice=applyStartingLoadout(s,{organ:key});
  assert.equal(choice.organ,key);
  assert.deepEqual(s.organs.filter(Boolean).map(p=>p.key),[key]);
  applyStartingLoadout(s,{organ:null});
  assert.equal(s.organs.filter(Boolean).length,0);
 }
 const s=run();meta(s.profile).overruns=3;
 assert.equal(validLoadout(s.profile,{organ:'digestion'}).organ,null);
});
