import test from 'node:test';
import assert from 'node:assert/strict';
import {createRun,addXP,chooseUpgrade,receiveDamage,spawnEnemy,step,attack} from '../src/game.js';
import {stats,weaponStats,createPart,equip,unequip,swapBody,upgrade} from '../src/assembly.js';
import {ABILITIES,FALLBACKS,learn,modifiers} from '../src/systems/abilities.js';
import {eligible,rollChoices,abilityCards,xpRequired} from '../src/systems/progression.js';
import {tickHealth,vampireHit,healthView} from '../src/systems/health.js';
import {onHit,enemyPace,tickEffects} from '../src/systems/effects.js';
import {enemyBalance,WAVE_RULES} from '../src/systems/balance.js';
import {tickWaves} from '../src/systems/waves.js';
const run=()=>createRun(undefined,'survival',88);
const install=(s,key,slot=0)=>{const p=createPart(s,key);s.inventory.push(p);assert.ok(equip(s,p.id,slot));return p;};
test('two whole lives; simultaneous contacts and protected hits do not charge armor',()=>{const s=run();assert.equal(s.hp,2);receiveDamage(s,10);assert.equal(s.hp,1);for(let i=0;i<20;i++)receiveDamage(s,1);assert.equal(s.hp,1);assert.equal(s.health.hits,1);s.time=.49;assert.equal(receiveDamage(s,1),'ignored');assert.equal(s.hp,1);s.time=.5;assert.equal(receiveDamage(s,1),'hurt');assert.equal(s.hp,0);assert.equal(healthView(s,2).segments.filter(Boolean).length,0);});
test('armor plates are spent before health and never recharge from hits',()=>{const s=run();learn(s,'vitality.1');assert.equal(receiveDamage(s,1),'armor');assert.equal(s.hp,2);assert.equal(healthView(s,2,stats(s).armor).armor,.5);s.time=1;assert.equal(receiveDamage(s,1),'armor');s.time=2;assert.equal(receiveDamage(s,1),'hurt');assert.equal(s.hp,1);s.time=100;tickHealth(s,stats(s));assert.equal(healthView(s,2,stats(s).armor).armor,0);});
test('shield transfer retains recharge and cannot be refilled by swapping',()=>{const s=run(),p=install(s,'shield');tickHealth(s,stats(s));s.time=11.99;tickHealth(s,stats(s));assert.equal(p.shieldCharge,0);s.time=12;tickHealth(s,stats(s));assert.equal(receiveDamage(s,1),'shield');unequip(s,'organs',0);equip(s,p.id,0);tickHealth(s,stats(s));assert.equal(p.shieldCharge,0);assert.equal(s.hp,2);});
test('capacity upgrades and body changes preserve wounds including clipped overflow',()=>{const s=run();receiveDamage(s,1);upgrade(s,s.body.id,'capacity');assert.equal(s.hp,1);assert.equal(upgrade(s,s.body.id,'hp'),false);const b=createPart(s,'bastion');s.inventory.push(b);swapBody(s,b.id);assert.equal(stats(s).hp-s.hp,1);});
test('regen heals one segment each 15 seconds; fatal hit is never healed in the same tick',()=>{const s=run();learn(s,'vitality.2');receiveDamage(s,1);s.time=14.99;tickHealth(s,stats(s));assert.equal(s.hp,1);s.time=15;tickHealth(s,stats(s));assert.equal(s.hp,2);s.hp=0;s.time=30;tickHealth(s,stats(s));assert.equal(s.hp,0);});
test('vampirism requires 30 hits and a 30 second cooldown',()=>{const s=run();s.body.tier=2;s.hp=stats(s).hp;s.hp=1;for(let i=0;i<29;i++)vampireHit(s,stats(s));assert.equal(s.hp,1);vampireHit(s,stats(s));assert.equal(s.hp,2);for(let i=0;i<40;i++)vampireHit(s,stats(s));assert.equal(s.hp,2);s.time=30;vampireHit(s,stats(s));assert.equal(s.hp,3);});
test('revival is once per run, not once per equipment instance',()=>{const s=run();learn(s,'vitality.3');s.hp=1;receiveDamage(s,1);assert.equal(s.hp,1);assert.ok(s.health.revived);s.time=3;receiveDamage(s,1);assert.equal(s.hp,0);});
test('51 unique nodes, finals unlock through either path, siblings stay available',()=>{assert.equal(Object.keys(ABILITIES).length,51);const s=run();assert.ok(!eligible(s,ABILITIES['fire.3']));learn(s,'fire.0');learn(s,'fire.2');assert.ok(eligible(s,ABILITIES['fire.1']));assert.ok(eligible(s,ABILITIES['fire.3']));learn(s,'fire.3');assert.ok(!eligible(s,ABILITIES.plasma));learn(s,'electric.3');assert.ok(eligible(s,ABILITIES.plasma));});
test('five unique offers across seeds and depleted catalogue; fallback never adds life',()=>{for(let seed=0;seed<100;seed++){const s=createRun(undefined,'survival',seed);rollChoices(s);assert.equal(new Set(s.choices.map(c=>c.id)).size,5);for(const c of s.choices)assert.ok(eligible(s,ABILITIES[c.id]));s.abilities.learned=Object.keys(ABILITIES);rollChoices(s);assert.equal(new Set(s.choices.map(c=>c.id)).size,5);assert.ok(s.choices.every(c=>FALLBACKS[c.id]&&!FALLBACKS[c.id].bonus.hp));}});
test('projectile requirements depend on installed weapons, learned powers persist',()=>{const s=run();s.arms=[null,null];assert.ok(!eligible(s,ABILITIES['projectiles.0']));install(s,'rocket');assert.ok(eligible(s,ABILITIES['projectiles.0']));learn(s,'projectiles.0');assert.ok(!eligible(s,ABILITIES['projectiles.1']));install(s,'seed',1);assert.ok(eligible(s,ABILITIES['projectiles.1']));s.arms=[];assert.equal(modifiers(s).extra,1);});
test('XP queue pauses simulation and card API remains valid across consecutive selections',()=>{const s=run();addXP(s,xpRequired(1)+xpRequired(2));assert.equal(s.pending,2);assert.equal(abilityCards(s).length,5);step(s,1);assert.equal(s.time,0);assert.equal(chooseUpgrade(s,-1),false);chooseUpgrade(s,0);chooseUpgrade(s,0);assert.equal(s.pending,0);assert.equal(s.abilities.learned.length,2);assert.equal(chooseUpgrade(s,0),false);});
test('burn refreshes strongest value, cold caps bosses, secondary damage cannot recurse',()=>{const s=run();s.rng=()=>0;for(const id of ['fire.0','cold.0','cold.3'])learn(s,id);const e=spawnEnemy(s,'boss',{x:2,z:0});for(let i=0;i<3;i++)onHit(s,e,10,()=>{});assert.equal(e.burn.dps,2);onHit(s,e,5,()=>{});assert.equal(e.burn.dps,2);assert.equal(enemyPace(s,e),.85);let damage=0;s.time=.1;tickEffects(s,.1,(_,d)=>damage+=d);assert.equal(damage,.2);assert.deepEqual(s.abilities.attacks,{});});
test('extra projectiles use current weapon and repeats do not consume ammo or count attacks',()=>{const s=run();s.arms=[createPart(s,'seed')];learn(s,'projectiles.0');const e=spawnEnemy(s,'normal',{x:5,z:0});e.hp=1000;attack(s,0);assert.equal(s.shots.length,2);assert.equal(s.abilities.attacks[s.arms[0].id],1);const ammo=s.arms[0].ammo;attack(s,0,stats(s),s.arms[0]);assert.equal(s.arms[0].ammo,ammo);assert.equal(s.abilities.attacks[s.arms[0].id],1);});
test('summons attack with bounded population and obey pause',()=>{const s=run();learn(s,'summons.0');learn(s,'summons.1');const e=spawnEnemy(s,'normal',{x:3,z:0});e.hp=1000;for(let i=0;i<20;i++){s.time+=.1;tickEffects(s,.1,(q,d)=>q.hp-=d);}assert.equal(s.abilities.companions.length,2);assert.ok(e.hp<1000);const before=JSON.stringify(s.abilities);s.pending=1;step(s,1);assert.equal(JSON.stringify(s.abilities),before);});
test('waves use time only and capped spawn credit never accumulates a debt',()=>{assert.equal(enemyBalance(2400).damage,1);assert.equal(enemyBalance(2400,'normal','fast').role,'fast');const s=run();s.enemies=Array.from({length:WAVE_RULES.cap},()=>({hp:1}));s.time=100;let count=0;tickWaves(s,10,()=>count++);assert.equal(count,0);assert.equal(s.spawnCredit,0);s.enemies=[];tickWaves(s,.01,()=>count++);assert.equal(count,0);});
test('same seeds yield identical choices and waves independent of learned power',()=>{const a=run(),b=run();learn(a,'might.0');for(const s of [a,b]){s.time=960;s.nextElite=2000;s.nextBoss=2000;}const aa=[],bb=[];tickWaves(a,1,(...x)=>aa.push(x));tickWaves(b,1,(...x)=>bb.push(x));assert.deepEqual(aa,bb);});
test('restart clears learned powers, shield and armor counters without changing permanent profile',()=>{const s=run();learn(s,'vitality.3');s.health.armorSpent=1;s.profile.achievements.push('example');const next=createRun(s.profile);assert.deepEqual(next.abilities.learned,[]);assert.equal(next.health.armorSpent,0);assert.equal(next.hp,2);assert.deepEqual(next.profile.achievements,['example']);});
test('new rank bonuses cannot be farmed by repeatedly installing a low-health body',()=>{const s=run(),b=createPart(s,'bastion');s.inventory.push(b);swapBody(s,b.id);const large=s.body,small=s.inventory.find(p=>p.key==='wanderer');s.hp=1;s.health.missing=2;swapBody(s,small.id);assert.equal(s.hp,0);swapBody(s,large.id);assert.equal(s.hp,1);assert.equal(s.health.missing,2);});
test('fallback selection still spends exactly one pending level',()=>{const s=run();s.abilities.learned=Object.keys(ABILITIES);addXP(s,18);const id=s.choices[0].id;assert.ok(chooseUpgrade(s,0));assert.equal(s.abilities.minor[id],1);assert.equal(s.pending,0);assert.equal(stats(s).hp,3);});
test('short melee hands can hit the surface of large bosses without entering contact distance',()=>{const s=run();s.arms=[createPart(s,'drill')];const e=spawnEnemy(s,'boss',{x:3.5,z:0});const hp=e.hp;attack(s,0);assert.ok(e.hp<hp);assert.ok(Math.hypot(e.x,e.z)>e.radius+1);});
test('stale incompatible offer rejects atomically without consuming an earned choice',()=>{const s=run();addXP(s,18);s.choices=[{id:'projectiles.0'}];s.arms=[null,null];const before=s.pending;assert.equal(chooseUpgrade(s,0),false);assert.equal(s.pending,before);assert.deepEqual(s.abilities.learned,[]);});
test('final boss is scheduled at forty minutes even when an earlier boss survives',()=>{const s=run();spawnEnemy(s,'boss',{x:10,z:0});s.time=2400;s.nextBoss=2400;s.nextElite=2400;const spawned=[];tickWaves(s,.01,(kind)=>spawned.push(kind));assert.deepEqual(spawned,['final']);assert.equal(s.nextBoss,2880);});
test('late XP pacing keeps thresholds increasing and preserves overflow across the curve joins',()=>{
 let previous=0;
 for(let level=1;level<=100;level++){
  const cost=xpRequired(level);assert.ok(Number.isInteger(cost)&&cost>previous);previous=cost;
 }
 for(const level of [21,28]){
  const s=run();s.level=level;
  addXP(s,xpRequired(level)+xpRequired(level+1)+7);
  assert.equal(s.level,level+2);assert.equal(s.xp,7);assert.equal(s.pending,2);
  assert.equal(abilityCards(s).length,5);
 }
 assert.equal(xpRequired(1),18);assert.equal(xpRequired(2),28);
});
