import test from 'node:test';
import assert from 'node:assert/strict';
import {createRun,attack,spawnEnemy} from '../src/game.js';
import {createPart} from '../src/assembly.js';
import {bodyRadius} from '../src/elevation.js';
import {queueWhipStrike,tickWhipStrikes} from '../src/systems/whip-pull.js';
import {createMeleeAnimation} from '../src/melee-animation.js';
import {createWhipVfx,alignWhipVfx,updateWhipVfx} from '../src/whip-vfx.js';
import * as T from 'three';
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`);
function fixture(){const s=createRun(undefined,'survival',123);s.player={x:0,y:0,z:0,facing:0};s.arms=[createPart(s,'whip'),createPart(s,'whip')];s.organs=[];s.encounters={nodes:[]};s.world={walkable:()=>true,canMove:()=>true,heightAt:()=>0,lineClear:()=>true};s.rng=()=>.99;s.events=[];return s;}
const event=(p,s)=>({type:'melee-windup',key:'whip',source:p.id,x:0,y:0,z:0,tx:0,ty:0,tz:7,at:s.time});
const targetable=(_,e)=>e.hp>0;
const damage=(_,e,w)=>{e.hp-=w.damage;return true;};
const weapon={key:'whip',damage:1,range:8,angle:2.8,interval:.9};
function enemy(s,kind='normal',x=0,z=7){const e={id:s.enemies.length+1,kind,x,y:0,z,radius:.48,hp:100};s.enemies.push(e);return e;}
test('each hand counts primary attacks independently; reload and echo do not change cycle',()=>{const s=fixture(),[a,b]=s.arms;for(let i=1;i<=6;i++){const e=event(a,s);queueWhipStrike(s,a,weapon,e);assert.equal(e.whipGather,i%3===0);const echo=event(a,s);queueWhipStrike(s,a,weapon,echo,true);assert.equal(echo.whipGather,false);a.reloadRemaining=1;}assert.equal(a.whipAttacks,6);assert.equal(b.whipAttacks,undefined);const e=event(b,s);queueWhipStrike(s,b,weapon,e);assert.equal(e.whipGather,false);});
test('damage occurs at sweep contact, then gathers survivors with normal/elite caps and boss immunity',()=>{const s=fixture(),p=s.arms[0];p.whipAttacks=2;const a=enemy(s),b=enemy(s,'elite',1,7),boss=enemy(s,'boss',-1,7),dead=enemy(s,'normal',.2,7);dead.hp=1;queueWhipStrike(s,p,weapon,event(p,s));const start=a.z;s.time+=.13;tickWhipStrikes(s,damage,targetable);assert.equal(a.hp,100);s.time+=.01;tickWhipStrikes(s,damage,targetable);assert.equal(a.hp,99);near(a.z,start);s.time+=.1;tickWhipStrikes(s,damage,targetable);assert.ok(a.whipPull);assert.ok(b.whipPull);assert.equal(boss.whipPull,undefined);assert.equal(dead.whipPull,undefined);s.time+=.19;tickWhipStrikes(s,damage,targetable);near(a.z,weapon.range+bodyRadius(s));assert.ok(Math.hypot(a.x,a.z)>5);assert.ok(Math.hypot(b.x-1,b.z-7)<=1+1e-7);near(boss.z,7);assert.equal(a.whipPull,undefined);});
test('pull obeys obstacles and keeps its aim when the player moves',()=>{const s=fixture(),p=s.arms[0];p.whipAttacks=2;const e=enemy(s);s.world.canMove=(a,b)=>b.z<=7.4;queueWhipStrike(s,p,weapon,event(p,s));s.time+=.25;tickWhipStrikes(s,damage,targetable);s.player.x=10;s.time+=.2;tickWhipStrikes(s,damage,targetable);assert.ok(e.z<=7.4);near(e.x,0);});
test('sector excludes targets behind and occluded targets; removed weapons cancel pending contact',()=>{const s=fixture(),p=s.arms[0];const front=enemy(s),back=enemy(s,'normal',0,-7);s.world.lineClear=()=>false;queueWhipStrike(s,p,weapon,event(p,s));s.time+=.5;tickWhipStrikes(s,damage,targetable);near(front.hp,100);near(back.hp,100);s.world.lineClear=()=>true;queueWhipStrike(s,p,weapon,event(p,s));s.arms=[];s.time+=.5;tickWhipStrikes(s,damage,targetable);near(front.hp,100);});
test('actual attacks queue contact and primary third strike; echo neither counts nor gathers',()=>{const s=fixture();s.arms=[s.arms[0]];const e=enemy(s,'normal',0,4);attack(s,.01);near(e.hp,100);assert.equal(s.arms[0].whipAttacks,1);assert.equal(s.events.find(e=>e.type==='melee-windup').whipGather,false);attack(s,0,undefined,s.arms[0]);assert.equal(s.arms[0].whipAttacks,1);assert.equal(s.whipStrikes.at(-1).event.whipGather,false);});
test('animation carries third strike, grabs, duration and mirrors both hands; VFX finite at reduced motion',()=>{for(const duration of [.42,.1]){const a=createMeleeAnimation(),p={id:1},s={time:0};a.attack({...event(p,s),duration,whipGather:true},0);const e={x:0,y:0,z:3,radius:.48,hp:100};a.attack({type:'whip-grab',source:1,targets:[e]},duration*.55);const left=a.pose(1,duration*.7,-1),right=a.pose(1,duration*.7,1);near(left.yaw,-right.yaw);assert.equal(right.targets[0],e);assert.equal(right.whipGather,true);const hero=new T.Group(),arm=new T.Group(),root=createWhipVfx();hero.add(arm);arm.add(root);for(const reduced of [false,true]){alignWhipVfx(root,arm,right,hero);updateWhipVfx(root,right,reduced);assert.ok([...root.userData.cable.geometry.attributes.position.array].every(Number.isFinite));assert.equal(root.userData.hooks.visible,true);}assert.equal(a.pose(1,duration),null);updateWhipVfx(root,null);assert.equal(root.visible,false);}});

test('normal pull caps at five metres and gather point follows effective weapon range',()=>{const s=fixture(),p=s.arms[0];p.whipAttacks=2;const e=enemy(s,'normal',-6,5);queueWhipStrike(s,p,weapon,event(p,s));s.time+=.25;tickWhipStrikes(s,damage,targetable);s.time+=.2;tickWhipStrikes(s,damage,targetable);near(Math.hypot(e.x+6,e.z-5),5);assert.ok(e.x<0);});

test('an echo cannot restart the ongoing third-strike animation',()=>{const a=createMeleeAnimation(),s={time:0},p={id:1};a.attack({...event(p,s),whipGather:true,duration:.42},0);assert.equal(a.attack({...event(p,s),at:.15,echo:true,whipGather:false,duration:.42},.15),false);assert.equal(a.pose(1,.2).whipGather,true);});

test('sweep reaches the actual gather distance even when the primary target is nearby',()=>{const hero=new T.Group(),arm=new T.Group(),root=createWhipVfx();hero.add(arm);arm.add(root);arm.position.x=.7;const strike={phase:.32,aim:0,originX:0,originZ:0,strikeRange:6,tx:0,ty:0,tz:2,targetRadius:.48};alignWhipVfx(root,arm,strike,hero);updateWhipVfx(root,strike);hero.updateMatrixWorld(true);const tip=root.localToWorld(root.userData.points.at(-1).clone());near(tip.z,6);near(tip.x,0);});
