import test from 'node:test';
import assert from 'node:assert/strict';
import {createWorldRun,stepWorldRun} from '../src/world-run.js';
import {spawnEnemy,hurtEnemy,randomLoot,receiveDamage} from '../src/game.js';
import {findPath,clearSegment,navigateEnemy} from '../src/world-navigation.js';
import {equipGround,createPart,preferredSlot,stats} from '../src/assembly.js';
import {tickEnemyRanged,tickHostileShots} from '../src/systems/waves.js';
import {MISSION_ENEMY_MULTIPLIER,MISSION_ENTRY_MAX_Z_OFFSET,MISSION_ENTRY_MIN_Z_OFFSET,MISSION_HALF_WIDTH,MISSION_ROOM_STRENGTH_STEP,missionEntryPosition,missionRoomStrength,strengthenMissionEnemy} from '../src/mission-run.js';
import {bodyRadius,movePlayer} from '../src/elevation.js';
import {MISSION_ENVIRONMENTS} from '../src/mission-environment.js';
const hooks=s=>({spawn:(...a)=>spawnEnemy(s,...a),loot:()=>randomLoot(s)});
const near=(actual,expected,epsilon=1e-9)=>assert.ok(Math.abs(actual-expected)<=epsilon,`${actual} != ${expected}`);
const defeatFloor=(s,floor)=>{while(true){const alive=s.enemies.filter(e=>floor.members.includes(e.id)&&e.hp>0);if(!alive.length)return;for(const enemy of alive)hurtEnemy(s,enemy,1e9);}};
test('mission world is a 25-room northbound corridor with its own environment',()=>{for(const seed of [1,77,20260907]){const s=createWorldRun(undefined,'core',seed),environment=MISSION_ENVIRONMENTS.core;assert.equal(s.world.tiles.length,25);assert.deepEqual(s.world.tiles.map(t=>t.z),Array.from({length:25},(_,i)=>i===0?0:-i*64));assert.deepEqual([...new Set(s.world.tiles.map(t=>t.biome))],[environment.biome]);assert.deepEqual([...new Set(s.world.tiles.map(t=>t.environmentId))],[environment.id]);assert.ok(s.world.tiles.every(t=>t.x===0));}});
test('mission corridor has fixed screen-width sides and cannot scroll into lateral space',()=>{const s=createWorldRun(undefined,'core',8),radius=bodyRadius(s);assert.deepEqual(s.world.playBounds,{minX:-MISSION_HALF_WIDTH,maxX:MISSION_HALF_WIDTH});assert.equal(s.world.walkable(MISSION_HALF_WIDTH,22,.01),false);for(let i=0;i<100;i++)movePlayer(s,0,1,0);assert.ok(s.player.x<=MISSION_HALF_WIDTH-radius+1e-6);for(let i=0;i<200;i++)movePlayer(s,0,-1,0);assert.ok(s.player.x>=-MISSION_HALF_WIDTH+radius-1e-6);});
test('a floor gate opens only after every enemy in that room is defeated',()=>{const s=createWorldRun(undefined,'core',7);stepWorldRun(s,0);const floor=s.mission.floorsState[0];assert.equal(floor.state,'active');assert.equal(s.world.walkable(0,-32),false);defeatFloor(s,floor);s.xpDrops=[];s.pending=0;stepWorldRun(s,0);assert.equal(floor.state,'cleared');assert.equal(s.world.walkable(0,-32),true);assert.equal(s.mission.floorsState[1].state,'ready');});
test('entering the next mission room closes the previous gate and prevents return',()=>{const s=createWorldRun(undefined,'core',3);stepWorldRun(s,0);const floor=s.mission.floorsState[0],gateZ=-32;defeatFloor(s,floor);s.xpDrops=[];s.pending=0;stepWorldRun(s,0);assert.equal(s.world.walkable(0,gateZ),true);s.player={x:0,y:0,z:-44};stepWorldRun(s,0);assert.equal(s.mission.floorsState[1].state,'active');assert.equal(s.mission.floorsState[1].entered,true);assert.equal(s.world.walkable(0,gateZ),false);assert.equal(s.world.canMove({x:0,z:gateZ-4},{x:0,z:gateZ+4},.8),false);s.player={x:0,y:0,z:gateZ-4};movePlayer(s,1,0,8);assert.ok(s.player.z<gateZ);});
test('the first mission room keeps its budget while survival begins with only the five boss habitats',()=>{const m=createWorldRun(undefined,'core',3),s=createWorldRun(undefined,'survival',3);stepWorldRun(m,0);for(let i=0;i<150;i++)stepWorldRun(s,.1);assert.equal(m.metrics.spawned,(m.mission.floorsState[0].roster.roles.length+1)*MISSION_ENEMY_MULTIPLIER);assert.equal(m.enemies.filter(e=>e.kind==='elite').length,1);assert.equal(m.ground.filter(g=>g.missionRoomLoot).length,0);assert.equal(s.metrics.spawned,5);});
test('mission defenders enter in formation from the far north edge and run into the room',()=>{const s=createWorldRun(undefined,'core',3);stepWorldRun(s,0);const floor=s.mission.floorsState[0],defenders=s.enemies.filter(e=>floor.members.includes(e.id));assert.ok(defenders.length>1);assert.ok(defenders.every(e=>e.z>=floor.z+MISSION_ENTRY_MIN_Z_OFFSET&&e.z<=floor.z+MISSION_ENTRY_MAX_Z_OFFSET));assert.ok(defenders.every(e=>e.missionArrival));const before=defenders.reduce((sum,e)=>sum+e.z,0)/defenders.length;for(let i=0;i<60;i++)stepWorldRun(s,1/60);const after=defenders.reduce((sum,e)=>sum+e.z,0)/defenders.length;assert.ok(after>before+.5,{before,after});});
test('far-edge mission entry lanes stay walkable in every room and environment',()=>{for(const mode of ['garden','quarantine','core','nursery','mother'])for(const seed of [1,42,20260909]){const s=createWorldRun(undefined,mode,seed);for(const floor of s.mission.floorsState)for(let slot=0;slot<27;slot++){const p=missionEntryPosition(s.world,floor,slot);assert.ok(p,`${mode}/${seed}/${floor.index}/${slot}`);assert.ok(s.world.walkable(p.x,p.z,1),`${mode}/${seed}/${floor.index}/${slot}`);assert.ok(p.z>=floor.z+MISSION_ENTRY_MIN_Z_OFFSET&&p.z<=floor.z+MISSION_ENTRY_MAX_Z_OFFSET,`${mode}/${seed}/${floor.index}/${slot}`);}}});
test('every next mission room compounds enemy health by seven percent while attack stays fixed',()=>{for(let index=0;index<25;index++){near(missionRoomStrength(index),Math.pow(1+MISSION_ROOM_STRENGTH_STEP,index));if(index)near(missionRoomStrength(index)/missionRoomStrength(index-1),1.07);}const sample={hp:100,maxHp:100,damage:10};strengthenMissionEnemy(sample,2);near(sample.hp,114.49);near(sample.maxHp,114.49);near(sample.damage,10);const s=createWorldRun(undefined,'core',3),m=s.mission;m.currentFloor=1;m.floorsState[0].state=s.exploration.groups[0].state='cleared';m.floorsState[1].state=s.exploration.groups[1].state='ready';s.player={x:0,y:0,z:m.floorsState[1].z+20};stepWorldRun(s,0);const defenders=s.enemies.filter(e=>m.floorsState[1].members.includes(e.id));assert.ok(defenders.length);assert.ok(defenders.every(e=>e.missionRoomStrength===1.07));const attacker=defenders[0],st=stats(s),before=s.hp;s.health.armorSpent=st.armor;receiveDamage(s,attacker.damage,st,attacker);near(s.hp,before-attacker.damage);});
test('mission ranged projectiles keep base damage and their room tag',()=>{const s=createWorldRun(undefined,'core',3);s.mission.complete=true;s.exploration.groups=[];s.enemies=[];s.player={x:5,y:0,z:0};const enemy=strengthenMissionEnemy(spawnEnemy(s,'normal',{x:0,z:0},'ranged'),1);s.time=2;tickEnemyRanged(s,enemy,s.player);assert.equal(s.hostileShots.length,1);const shot=s.hostileShots[0];near(shot.damage,enemy.damage);assert.equal(shot.missionScaled,true);let hit=null;tickHostileShots(s,1,value=>hit=value);assert.equal(hit,shot);});
test('A star and enemy movement go around an obstacle using the same footprint',()=>{const world={walkable:(x,z,r=1)=>Math.abs(x)<80&&Math.abs(z)<80&&Math.hypot(x,z)>8+r};const start={x:-20,z:0},goal={x:20,z:0},path=findPath(world,start,goal,1);assert.ok(path.some(p=>Math.abs(p.z)>=10));let previous=start;for(const p of path){assert.ok(clearSegment(world,previous,p,1));previous=p;}const s={world,time:0},e={...start,id:1,radius:1};for(let i=0;i<400;i++){s.time+=.05;navigateEnemy(s,e,goal,4,.05);assert.ok(world.walkable(e.x,e.z,1));}assert.ok(Math.hypot(e.x-goal.x,e.z-goal.z)<1);});
test('quick equip prefers empty compatible socket and rejects duplicate actions atomically',()=>{const s=createWorldRun(undefined,'core',7),p=createPart(s,'regen');s.ground.push({id:888,part:p,...s.player});const slot=preferredSlot(s,p);assert.equal(slot,0);assert.equal(equipGround(s,888,99),false);assert.equal(s.inventory.length,0);assert.equal(s.ground.length,1);assert.equal(equipGround(s,888,slot),true);assert.equal(equipGround(s,888,slot),false);assert.equal(s.organs.filter(q=>q?.id===p.id).length,1);assert.equal(s.ground.length,0);});
test('legacy ranged enemy fires immediately and recovery blocks a repeat',()=>{const s=createWorldRun(undefined,'core',7);s.player={x:5,z:0};const e=spawnEnemy(s,'normal',{x:0,z:0},'ranged');s.time=2;tickEnemyRanged(s,e,s.player);assert.equal(e.windup,undefined);assert.equal(s.hostileShots.length,1);assert.equal(s.hostileShots[0].key,'legacy');assert.equal(s.hostileShots[0].dz,0);assert.equal(s.hostileShots[0].dx,1);s.player.z+=5;tickEnemyRanged(s,e,s.player);assert.equal(s.hostileShots.length,1);s.time=5.49;tickEnemyRanged(s,e,s.player);assert.equal(s.hostileShots.length,1);s.time=5.5;tickEnemyRanged(s,e,s.player);assert.equal(s.hostileShots.length,2);assert.notEqual(s.hostileShots[1].dz,0);});
test('mission gates are simulation barriers, not destructible objective enemies',()=>{const s=createWorldRun(undefined,'core',42);stepWorldRun(s,0);assert.equal(s.enemies.some(e=>e.kind==='objective'),false);assert.equal(s.world.walkable(0,-32),false);assert.equal(s.world.walkable(29,-32),false);});

test('new survival run keeps only melee and does not auto-grant spawn loot',()=>{for(const seed of [1,42,20317]){const s=createWorldRun(undefined,'survival',seed);stepWorldRun(s,1/60);assert.deepEqual(s.arms.map(p=>p?.key??null),['claws',null]);assert.deepEqual(s.inventory,[]);assert.equal(stats(s).weight,24);}});

test('every mission and survival start without a digestion organ',()=>{for(const mode of ['garden','quarantine','core','nursery','mother']){const s=createWorldRun(undefined,mode,42);assert.deepEqual(s.organs,[null,null]);}assert.deepEqual(createWorldRun(undefined,'survival',42).organs,[null,null]);});

test('each mission starts at the south edge of its first themed room',()=>{for(const id of ['garden','quarantine','core','nursery','mother']){const s=createWorldRun(undefined,id,42);assert.deepEqual({x:s.player.x,z:s.player.z},{x:0,z:22});assert.equal(s.world.tiles.every(t=>t.biome===s.mission.biome),true);}});

test('ranged enemy below its stopping distance navigates around an obstacle without entering it',()=>{const s=createWorldRun(undefined,'core',42);s.world={landmarks:[],walkable:(x,z,r=1)=>Math.abs(x)<80&&Math.abs(z)<80&&Math.hypot(x,z)>2+r};s.exploration.groups=[];s.mission.complete=true;s.enemies=[];s.arms=[null,null];s.player={x:4,z:0};const enemy=spawnEnemy(s,'normal',{x:-4,z:0},'ranged',0);s.time=3;stepWorldRun(s,.05);assert.equal(enemy.windup,undefined);for(let i=0;i<300;i++)stepWorldRun(s,.05);assert.ok(Math.abs(enemy.z)>2);assert.ok(s.world.walkable(enemy.x,enemy.z,enemy.radius));});

test('failed path search observes its retry interval instead of searching every frame',()=>{let calls=0;const s={time:0,world:{walkable:()=>false,findPath:()=>{calls++;return[];}}},e={x:0,z:0,id:1,radius:1},target={x:10,z:0};for(let i=0;i<60;i++){s.time=i/60;navigateEnemy(s,e,target,3,1/60);}assert.equal(calls,1);s.time=1.2;navigateEnemy(s,e,target,3,1/60);assert.equal(calls,2);});

test('mission room enemies spawn on real walkable ground across seeds',()=>{for(let seed=1;seed<=100;seed++)for(const mode of ['core','nursery']){const s=createWorldRun(undefined,mode,seed);stepWorldRun(s,0);const floor=s.mission.floorsState[0];assert.equal(floor.members.length,(floor.roster.roles.length+1)*MISSION_ENEMY_MULTIPLIER);assert.equal(s.enemies.filter(e=>e.kind==='elite').length,1);for(const e of s.enemies)assert.ok(s.world.walkable(e.x,e.z,e.radius),`${mode}/${seed}/${e.groupId}`);}});
