import test from 'node:test';
import assert from 'node:assert/strict';
import {createWorldRun,stepWorldRun} from '../src/world-run.js';
import {tickExploration,tickDelivery} from '../src/exploration.js';
import {spawnEnemy,hurtEnemy,randomLoot} from '../src/game.js';
import {findPath,clearSegment,navigateEnemy} from '../src/world-navigation.js';
import {equipGround,createPart,preferredSlot,stats} from '../src/assembly.js';
import {tickEnemyRanged,RANGED_WARNING} from '../src/systems/waves.js';
import {ROADS} from '../src/world-layout.js';
const hooks=s=>({spawn:(...a)=>spawnEnemy(s,...a),loot:()=>randomLoot(s)});
test('shared routes are walkable across seeds and depot is genuinely locked',()=>{for(const seed of [1,77,20260907]){const s=createWorldRun(undefined,'core',seed);assert.equal(s.world.walkable(0,-448),false);assert.equal(s.world.walkable(32,-480),false);s.mission.open=true;for(const path of ROADS)for(let i=1;i<path.length;i++)assert.ok(clearSegment(s.world,{x:path[i-1][0],z:path[i-1][1]},{x:path[i][0],z:path[i][1]}),JSON.stringify(path));}});
test('both unlocking routes and both exits, optional stash omitted, pursuit occurs once',()=>{for(const approach of ['gate','relays'])for(const exit of ['far','near']){const s=createWorldRun(undefined,'core',7),m=s.mission;const before=stats(s);if(approach==='gate')hurtEnemy(s,m.nodes[5],10000);else for(const n of m.nodes.slice(3,5)){s.player={x:n.x,z:n.z};tickDelivery(s);}tickDelivery(s);assert.ok(m.open);s.player={x:m.nodes[0].x,z:m.nodes[0].z};tickDelivery(s);tickExploration(s,0,hooks(s));assert.equal(m.carrying,true);assert.equal(stats(s).speed,before.speed);assert.equal(stats(s).weight,before.weight);const pursuit=s.exploration.groups.find(g=>g.id==='pursuit');assert.equal(pursuit.members.length,6);const ids=[...pursuit.members];tickDelivery(s);tickExploration(s,0,hooks(s));assert.deepEqual(pursuit.members,ids);if(exit==='near'){s.player={...m.nodes[2]};assert.equal(tickDelivery(s),false);s.exploration.groups.find(g=>g.id==='near-exit').state='cleared';}else s.player={...m.nodes[1]};assert.equal(tickDelivery(s),true);assert.equal(m.extraction,exit);assert.equal(s.exploration.groups.find(g=>g.id==='stash').state,'unseen');}});
test('mission groups and drops persist across chunk unload, no time escalation or respawn',()=>{const s=createWorldRun(undefined,'core',3);s.time=490;s.player={x:0,z:315};tickExploration(s,0,hooks(s));const group=s.exploration.groups.find(g=>g.id==='stairs'),enemy=s.enemies.find(e=>e.groupId==='stairs');const control=createWorldRun(undefined,'core',3);control.player={x:0,z:315};tickExploration(control,0,hooks(control));assert.equal(enemy.maxHp,control.enemies.find(e=>e.groupId==='stairs').maxHp);for(const e of s.enemies.filter(e=>e.groupId==='stairs'))hurtEnemy(s,e,10000);tickExploration(s,0,hooks(s));const drops=s.ground.map(q=>q.id),spawned=s.metrics.spawned;s.player={x:900,z:900};for(let x=0;x<16;x++)s.world.chunk(x,12);s.player={x:0,z:315};tickExploration(s,0,hooks(s));assert.equal(group.state,'cleared');assert.equal(s.metrics.spawned,spawned);assert.deepEqual(s.ground.map(q=>q.id),drops);});
test('mission idle area is quiet while survival continuously spawns',()=>{const m=createWorldRun(undefined,'core',3),s=createWorldRun(undefined,'survival',3);for(let i=0;i<150;i++){stepWorldRun(m,.1);stepWorldRun(s,.1);}assert.equal(m.metrics.spawned,0);assert.ok(s.metrics.spawned>=8);});
test('A star and enemy movement go around an obstacle using the same footprint',()=>{const world={walkable:(x,z,r=1)=>Math.abs(x)<80&&Math.abs(z)<80&&Math.hypot(x,z)>8+r};const start={x:-20,z:0},goal={x:20,z:0},path=findPath(world,start,goal,1);assert.ok(path.some(p=>Math.abs(p.z)>=10));let previous=start;for(const p of path){assert.ok(clearSegment(world,previous,p,1));previous=p;}const s={world,time:0},e={...start,id:1,radius:1};for(let i=0;i<400;i++){s.time+=.05;navigateEnemy(s,e,goal,4,.05);assert.ok(world.walkable(e.x,e.z,1));}assert.ok(Math.hypot(e.x-goal.x,e.z-goal.z)<1);});
test('quick equip prefers empty compatible socket and rejects duplicate actions atomically',()=>{const s=createWorldRun(undefined,'core',7),p=createPart(s,'regen');s.ground.push({id:888,part:p,...s.player});const slot=preferredSlot(s,p);assert.equal(slot,0);assert.equal(equipGround(s,888,99),false);assert.equal(s.inventory.length,0);assert.equal(s.ground.length,1);assert.equal(equipGround(s,888,slot),true);assert.equal(equipGround(s,888,slot),false);assert.equal(s.organs.filter(q=>q?.id===p.id).length,1);assert.equal(s.ground.length,0);});
test('ranged warning locks direction for 0.7 seconds and only simulation time advances it',()=>{const s=createWorldRun(undefined,'core',7);s.player={x:5,z:480};const e=spawnEnemy(s,'normal',{x:0,z:480},'ranged');s.time=2;tickEnemyRanged(s,e,s.player);assert.equal(e.windup.at,2+RANGED_WARNING);s.player.z+=5;for(let i=0;i<10;i++)tickEnemyRanged(s,e,s.player);assert.equal(s.hostileShots.length,0);s.time=2.69;tickEnemyRanged(s,e,s.player);assert.equal(s.hostileShots.length,0);s.time=2.7;tickEnemyRanged(s,e,s.player);assert.equal(s.hostileShots.length,1);assert.equal(s.hostileShots[0].dz,0);assert.equal(s.hostileShots[0].dx,1);});
test('gate is destructible by ranged auto attacks at 60 Hz without projectile tunnelling',()=>{const s=createWorldRun(undefined,'core',42);s.exploration.groups=[];s.arms=[null,createPart(s,'seed')];s.player={x:0,z:-440};const gate=s.mission.nodes[5];for(let i=0;i<3600&&!s.mission.open;i++)stepWorldRun(s,1/60);assert.ok(gate.hp<=0);assert.equal(s.mission.open,true);});

test('new survival run keeps only melee and does not auto-grant spawn loot',()=>{for(const seed of [1,42,20317]){const s=createWorldRun(undefined,'survival',seed);stepWorldRun(s,1/60);assert.deepEqual(s.arms.map(p=>p?.key??null),['claws',null]);assert.deepEqual(s.inventory,[]);assert.equal(stats(s).weight,24);}});

test('nursery starts by the protected object and activates its finite attackers immediately',()=>{const s=createWorldRun(undefined,'nursery',42);assert.ok(Math.hypot(s.player.x-s.mission.nodes[0].x,s.player.z-s.mission.nodes[0].z)<10);stepWorldRun(s,1/60);const siege=s.exploration.groups.filter(g=>g.defense);assert.equal(siege.length,4);assert.ok(siege.every(g=>g.state==='active'&&g.members.length===5));assert.equal(s.mission.duration,480);});

test('ranged enemy below its stopping distance navigates around blocked firing lane',()=>{const s=createWorldRun(undefined,'core',42);s.world={landmarks:[],walkable:(x,z,r=1)=>Math.abs(x)<80&&Math.abs(z)<80&&Math.hypot(x,z)>2+r};s.exploration.groups=[];s.mission.complete=true;s.enemies=[];s.arms=[null,null];s.player={x:4,z:0};const enemy=spawnEnemy(s,'normal',{x:-4,z:0},'ranged',0);s.time=3;stepWorldRun(s,.05);assert.equal(enemy.windup,undefined);for(let i=0;i<100;i++)stepWorldRun(s,.05);assert.ok(Math.abs(enemy.z)>2);assert.ok(clearSegment(s.world,enemy,s.player,.05));});

test('failed path search observes its retry interval instead of searching every frame',()=>{let calls=0;const s={time:0,world:{walkable:()=>false,findPath:()=>{calls++;return[];}}},e={x:0,z:0,id:1,radius:1},target={x:10,z:0};for(let i=0;i<60;i++){s.time=i/60;navigateEnemy(s,e,target,3,1/60);}assert.equal(calls,1);s.time=1.2;navigateEnemy(s,e,target,3,1/60);assert.equal(calls,2);});

test('finite mission groups spawn outside geometry even when their fallback centre is obstructed',()=>{for(let seed=1;seed<=100;seed++)for(const mode of ['core','nursery']){const s=createWorldRun(undefined,mode,seed);for(const g of s.exploration.groups){if(g.state!=='unseen')continue;s.player={x:g.x,z:g.z};tickExploration(s,0,hooks(s));}for(const g of s.exploration.groups.filter(g=>g.state==='active'))assert.equal(g.members.length,g.roles.length);for(const e of s.enemies.filter(e=>e.kind!=='objective'))assert.ok(s.world.walkable(e.x,e.z,e.radius),`${mode}/${seed}/${e.groupId}`);}});
