import {e,button,icon,frame,meter,sectionLabel} from './atoms.js';
import {partArt,partGrid,resource} from './molecules.js';
import {CATALOG} from '../catalog.js';
import {meta} from '../systems/meta-progression.js';
import {ACHIEVEMENTS,ACHIEVEMENT_CATEGORIES,achievementById,achievementDone,achievementArt,achievementProgress,journal,visitedBiomes,completedEventTypes,BIOME_NAMES,earnedThisRun} from '../systems/achievements.js';
import {EVENTS} from '../systems/events/definitions.js';
import './achievements.css';

const footer=html=>`<footer class="ui-screen-footer">${html}</footer>`;
const art=(a,large=false)=>a.artKey?partArt(a.artKey,{className:`achievement-image ${large?'achievement-image--large':''}`,label:a.name}):`<img class="achievement-image ${large?'achievement-image--large':''}" src="${e(achievementArt(a))}" alt="${e(a.name)}" width="${large?512:80}" height="${large?512:80}" decoding="async" ${large?'fetchpriority="high"':'loading="lazy"'}>`;
const scopeLabel=a=>a.scope==='lifetime'?'За всё время':'За один забег';
const rewardVisual=a=>(a.reward.tokens?icon('reroll'):'')+e(rewardName(a));
const rewardName=a=>a.reward.tokens?'+1 жетон':a.reward.keys.map(key=>CATALOG[key].name).join(' · ');
function progressRows(a,values){return a.conditions.map((c,i)=>`<div class="achievement-condition"><div><span>${e(c.label)}</span><strong>${values[i]||0} / ${c.goal}</strong></div>${meter(values[i]||0,c.goal,{label:c.label})}</div>`).join('');}

export function profileScreen(s,p,params={}){
 const m=meta(p),doneCount=ACHIEVEMENTS.filter(a=>achievementDone(p,a)).length,filter=params.filter||'all';
 const list=ACHIEVEMENTS.filter(a=>filter==='all'||(filter==='done')===achievementDone(p,a));
 return `<section class="ui-screen-body meta-screen achievement-journal">${frame(`<div class="meta-avatar">${partArt('wanderer')}</div><div><h3>Садовник</h3><p>Журнал открытий</p></div><strong class="achievement-total">${doneCount}<small>/ ${ACHIEVEMENTS.length}</small></strong>`,{className:'meta-identity'})}<div class="meta-stats">${resource('Забеги',m.runs,'clock')}${resource('Победы',m.wins,'target')}${resource('Кубик',m.rerolls,'reroll')}</div>${sectionLabel('Достижения')}<nav class="achievement-filters" aria-label="Состояние достижений">${[['all','Все'],['todo','В процессе'],['done','Получено']].map(([id,label])=>button(label,{action:'achievement-filter','data-id':id,variant:filter===id?'selected':'quiet','aria-pressed':String(filter===id)})).join('')}</nav><div class="meta-achievements">${list.map(a=>{
 const done=achievementDone(p,a),values=achievementProgress(s,p,a),percent=Math.floor(values.reduce((n,v,i)=>n+v/a.conditions[i].goal,0)/a.conditions.length*100);
 return `<button type="button" class="ui-frame achievement-row ${done?'is-complete':''}" data-action="meta-achievement" data-id="${e(a.id)}" aria-label="${e(a.name)} · ${done?'Получено':'Подробнее'}">${art(a)}<span class="achievement-row-copy"><small>${e(ACHIEVEMENT_CATEGORIES[a.category])} · ${done?'✓ Получено':e(scopeLabel(a))}</small><strong>${e(a.name)}</strong><span class="achievement-reward-line">${rewardVisual(a)}</span>${done?'':`<span class="achievement-mini-progress"><i style="width:${percent}%"></i></span><small>${values.map((v,i)=>`${v}/${a.conditions[i].goal}`).join(' · ')} · ${a.scope==='run'?'Сейчас':'Всего'}</small>`}</span><span class="achievement-chevron" aria-hidden="true">›</span></button>`;
 }).join('')||'<p class="achievement-empty">Здесь пока нет достижений. Выберите другое состояние.</p>'}</div></section>${footer(button('Атлас',{action:'catalog'})+button('Подготовка',{action:'start',variant:'primary'}))}`;
}

export function achievementScreen(s,p,id){
 const a=achievementById(id)||ACHIEVEMENTS[0],done=achievementDone(p,a),j=journal(p),values=done?a.conditions.map(c=>c.goal):achievementProgress(s,p,a),best=j.best[a.id];
 const checklist=a.id==='meta:spring'?`<div class="achievement-checklist">${Object.entries(BIOME_NAMES).map(([id,name])=>`<span>${done||visitedBiomes(s).includes(id)?'✓':'○'} ${e(name)}</span>`).join('')}</div><p class="ui-note">События: ${completedEventTypes(s).map(type=>e(EVENTS[type].name)).join(' · ')||'пока нет'}</p>`:'';
 const discovery=a.id==='feat:secrets'?`<div class="achievement-checklist">${[['membrane','Мембрана · Мойка'],['slab','Плита · Трамбовка или Бур'],['nursery','Питомник · Сварочник']].map(([id,label])=>`<span>${done||j.secrets.includes(id)?'✓':'○'} ${label}</span>`).join('')}</div>`:a.id==='feat:natures'?`<div class="achievement-checklist">${[['hive','Улей'],['conductor','Проводник'],['mire','Топь']].map(([id,label])=>`<span>${done||j.mutations.includes(id)?'✓':'○'} ${label}</span>`).join('')}</div>`:'';
 const delivery={ground:'При первом открытии деталь появляется рядом с персонажем. Подберите её. Тип сохраняется в атласе.',inventory:'При первом открытии тип сохраняется в атласе, а экземпляр появляется в инвентаре текущего забега.',mission:'Награда выдаётся за победу над боссом миссии. Открытый тип затем может выпадать в выживании.'};
 return `<section class="ui-screen-body meta-screen achievement-detail"><div class="achievement-hero">${art(a,true)}<span class="achievement-state">${done?'✓ Получено':e(scopeLabel(a))}</span></div><div class="achievement-heading"><small>${e(ACHIEVEMENT_CATEGORIES[a.category])}</small><h3>${e(a.name)}</h3><p class="achievement-lore">${e(a.lore)}</p></div><p>${e(a.description)}</p><section class="achievement-progress-block" aria-label="Условия достижения"><h4>${done?'Выполнено':a.scope==='run'?'Текущий забег':'Общий прогресс'}</h4>${progressRows(a,values)}${checklist}${discovery}${!done&&a.scope==='run'?'<p class="ui-note">Условия должны быть выполнены в одном забеге. Прогресс разных забегов не складывается.</p>':''}${!done&&a.scope==='run'&&best?.some(n=>n>0)?`<p class="achievement-best">Лучший забег: ${best.map((v,i)=>`${v} / ${a.conditions[i].goal}`).join(' · ')}</p>`:''}</section><section class="achievement-reward-block"><h4>Награда</h4>${a.reward.tokens?`<div class="achievement-token">${resource('Жетон перевыбора',a.reward.tokens,'reroll')}</div><p>Один раз за достижение. Сохраняется между забегами и позволяет обновить выбор способностей или награды босса.</p>`:partGrid(a.reward.keys.map(key=>({key,name:CATALOG[key].name,action:'catalog-detail'})))+`<p class="ui-note">${e(delivery[a.reward.delivery])}</p><p class="ui-note">Если тип уже открыт, повторный экземпляр за это открытие не выдаётся.</p>`}</section>${done?`<p class="achievement-date">${j.dates[a.id]?'Получено · '+e(j.dates[a.id]):'Получено ранее · дата не записывалась'}</p>`:''}</section>${footer(button('Назад',{action:'back'})+(a.reward.keys?button('Деталь',{action:'catalog-detail','data-key':a.reward.keys[0]}):button('Подготовка',{action:'start',variant:'primary'})))}`;
}

export function achievementRunSummary(s){const list=earnedThisRun(s);return list.length?`<section class="achievement-run-summary"><h3>Достижения за забег</h3>${list.map(a=>`<button type="button" class="achievement-result-row" data-action="meta-achievement" data-id="${e(a.id)}">${art(a)}<span><strong>${e(a.name)}</strong><small>${rewardVisual(a)}</small></span><span aria-hidden="true">›</span></button>`).join('')}</section>`:'';}
