import {describePart} from './adapters.js';
import {EVENT_PRESENTATION,eventState,eventImage,eventGlyph} from '../gameplay-modules/event-presentation.js';
import {nearEncounter,availableEncounter,encounterLevel} from '../systems/events/proximity.js';
import {e,frame,button,badge,sectionLabel} from './atoms.js';
import {partGrid} from './molecules.js';
import {mutationView,affectedHands,removalWarning} from '../systems/mutations.js';
import {ENCOUNTERS,DEALS,nearbyEncounters,dealAllowed,challengeAllowed} from '../systems/encounters.js';
import {CATALOG} from '../catalog.js';
import {stats} from '../assembly.js';
export function mutationPanel(s){return `<details class="ui-mutations"><summary>Мутации тела · активных: ${mutationView(s).filter(f=>f.active).length}</summary>${mutationView(s).map(f=>frame(`<strong>${e(f.name)} ${badge(`${Math.min(3,f.count)}/3`)} ${f.active?'· Активна':''}</strong><p>${e(f.description)}</p><small>${f.keys.map(k=>e(CATALOG[k].name)).join(' · ')}</small>`,{className:'ui-mutation '+(f.active?'is-active':'')})).join('')}<p class="ui-note">Нужны 3 разных установленных типа. Снятие части комплекта отключает мутацию.</p></details>`;}
export function compatibility(s,p){if(!['returnNerve','commonNerve'].includes(p.key))return '';const names=affectedHands(s,p.key);return `<p class="ui-note ui-compatibility">${e(describePart(s,p).lines[0])}</p><p class="ui-note">Изменит руки: ${names.length?names.map(e).join(', '):'нет совместимых установленных рук'}.</p>`;}
export function mutationWarning(before,after){const names=removalWarning(before,after);return names.length?`<p class="ui-warning">Отключится мутация: ${names.map(e).join(', ')}.</p>`:'';}
export function encounterList(s){const nearby=nearbyEncounters(s);return `<section class="ui-screen-body ui-encounters">${nearby.length?nearby.map(n=>frame(`<small>${eventGlyph(n)} ${e(eventState(n))}</small><h3>${e(ENCOUNTERS[n.type].name)}</h3><p>${e(ENCOUNTERS[n.type].hint)}</p>${button(n.state==='reward'?'Награда':'Осмотреть',{action:'encounter-detail','data-id':n.id})}`,{className:'ui-encounter'})).join(''):'<p>Подойдите к отмеченному объекту. События отмечены на карте знаком ✚, секреты нужно искать самостоятельно.</p>'}${s.encounters?.active?.dungeon?'':button('Карта',{action:'map'})}</section>`;}
const challengeRules={
 infection:['Уклоняйтесь от живучих преследователей. Убивать их не обязательно.','Оставайтесь внутри круга 30 секунд.','Регенерация и вампиризм отключены.','Выход приостанавливает прогресс.'],
 sealed:['Продержитесь 45 секунд и победите всех врагов.','После входа выйти из арены нельзя.'],
 hunt:['Победите отмеченную элиту за 60 секунд.','Время вышло — награда потеряна.'],
 race:['Доберитесь до финиша на дальней стороне карты.','На пути три группы врагов. Убивать всех не обязательно.','Лимит одинаковый для всех сборок. Медленная сборка рискует не успеть.','Стрелка и карта показывают финиш. Обычные волны на паузе.','Детали не подбираются автоматически до конца испытания. Разгрузите инвентарь перед стартом.'],
 dungeon_roots:['Единый этаж корневых тоннелей: коридоры расходятся в разные стороны, петляют и заканчиваются тупиками. Комнат и ворот нет.','При входе survival-таймер и мировой директор останавливаются.','Сразу расставлены 12 усиленных элит. Каждый оставляет один предмет; редкость бросается дважды, сохраняется лучший результат.','Можно выйти через вход и вернуться: живые враги и прогресс сохраняются.'],
 dungeon_catacombs:['Единый этаж техногенных тоннелей: коридоры расходятся в разные стороны, петляют и заканчиваются тупиками. Комнат и ворот нет.','При входе survival-таймер и мировой директор останавливаются.','Сразу расставлены 18 усиленных элит. Каждый оставляет один предмет; редкость бросается дважды, сохраняется лучший результат.','Можно выйти через вход и вернуться: живые враги и прогресс сохраняются.'],
};
function rewards(n,claim){return partGrid(n.rewards.map((key,id)=>({key,name:CATALOG[key].name,action:claim?'encounter-claim':'item-preview',id,tier:['','I','II','III'][n.rewardTier||1]})),{className:'event-rewards'});}
export function encounterDetail(s,id){
 const n=s.encounters?.nodes.find(n=>n.id===id);if(!n)return '<section class="ui-screen-body ui-event-detail">Событие недоступно.</section>';
 const d=ENCOUNTERS[n.type],p=EVENT_PRESENTATION[n.type],near=nearEncounter(s,n,4);let body='',primary='';
 if(n.state==='reward'){body=`${sectionLabel('Награда — одна на выбор')}${rewards(n,true)}<p class="ui-note">Нажмите на деталь, чтобы посмотреть свойства и забрать. Остальные награды исчезнут.</p>${n.type==='slab'?'<p>Дополнительно: 30 биомассы.</p>':''}`;}
 else if(n.state==='ready'&&d.kind==='altar'){
  const deals=n.deals.filter(key=>Object.hasOwn(DEALS,key)),missionDeal=n.missionEvent&&deals.length===1&&deals[0]!=='fuse'?deals[0]:null;
  body=deals.map(key=>frame(`<h3>${e(DEALS[key].name)}</h3><p>${e(DEALS[key].description)}</p>${key==='fuse'?button('Выбрать руку',{action:'fuse-open',disabled:!s.arms.some(hand=>hand&&dealAllowed(s,n,'fuse',hand.id))}):missionDeal?'':button('Принять',{action:'deal-accept','data-key':key,variant:'danger',disabled:!dealAllowed(s,n,key)})}`,{className:'event-deal'})).join('')+'<p class="ui-note">Одна операция на этом алтаре. Недоступные сделки нельзя выбрать.</p>';
  if(missionDeal)primary=button('Принять',{action:'deal-accept','data-key':missionDeal,variant:'danger',disabled:!dealAllowed(s,n,missionDeal)});
 }else if(['ready','paused'].includes(n.state)&&d.kind==='challenge'){
  body=`<ul class="event-rules">${challengeRules[n.type].map(t=>`<li>${e(t)}</li>`).join('')}</ul>${sectionLabel(n.missionEvent?'Награда за испытание':'Награда — одна на выбор')}${n.rewardTier?`<p class="ui-note">Уровень детали: ${['','I','II','III'][n.rewardTier]||n.rewardTier}</p>`:''}${rewards(n,false)}${n.missionEvent?'<p class="ui-note">Одна показанная деталь выпадет только после победы.</p>':''}`;
  if(n.type==='race')body=`${n.race?`<p><strong>${Math.ceil(n.race.length)} м по маршруту · ${n.race.limit} с</strong></p><p>Скорость сборки: ${stats(s).speed.toFixed(1)} м/с</p>${stats(s).speed<n.race.length/n.race.limit?'<p class="ui-warning">Текущая сборка слишком медленная для этого лимита.</p>':''}`:n.raceUnavailable?'<p class="ui-warning">Проходимый маршрут не найден. Испытание недоступно.</p>':'<p class="ui-note">Маршрут рассчитывается у старта.</p>'}${body}`;
  primary=button(n.state==='paused'?'Вернуться':'Начать',{action:'encounter-start',variant:'primary',disabled:!challengeAllowed(s,n)||n.type==='race'&&!n.race});
  if(near&&!challengeAllowed(s,n))body+=`<p class="ui-warning">${n.unlockLevel&&s.level<n.unlockLevel?'Доступно с уровня '+n.unlockLevel+'.':'Завершите бой с боссом, текущее испытание или выбор уровня.'}</p>`;
 }else {body=`<p>${e(({ready:d.hint,paused:'Прогресс сохранён. Можно вернуться через вход.',active:n.dungeon?(n.cleared?'Зачистка завершена. Выход открыт.':'Зачистка продолжается. Выйдите через вход, чтобы сохранить прогресс.'):'Испытание идёт. Вернитесь в игру, чтобы продолжить.',complete:d.kind==='altar'?'Сделка заключена. Алтарь больше недоступен в этом забеге.':'Событие завершено.',failed:n.skipped?'Вы отказались · проход открыт без награды':'Время вышло. Награда потеряна. Повторить испытание в этом забеге нельзя.'})[n.state])}</p>`;if(n.dungeon&&n.state==='active')primary=button('Выйти',{action:'dungeon-exit',variant:'primary'});}
 if(!near&&!['complete','failed'].includes(n.state)){body='<p class="ui-warning">Подойдите к объекту, чтобы взаимодействовать.</p>'+body;primary=button('Маршрут',{action:'event-route',variant:'primary'});}
 const exit=n.missionEvent&&n.state==='ready'?button('Отказаться',{action:'mission-event-skip'}):button(n.state==='active'?'Продолжить':'Позже',{action:'resume'});
 return `<section class="ui-screen-body ui-event-detail"><div class="event-heading">${p&&!n.missionEvent?`<p class="ui-warning">Вход с ${encounterLevel(n)}-го уровня · ваш уровень ${s.level}</p>`:''}<span class="ui-eyebrow">${eventGlyph(n)} ${p?'Событие · '+e(p.category):'Секрет'} · ${e(p&&!availableEncounter(s,n)?'Закрыто':eventState(n))}</span><h3>${e(d.name)}</h3></div>${p?`<img class="event-illustration event-illustration--${e(n.type)}" src="${eventImage(n.type)}" alt="Иллюстрация события «${e(d.name)}»">`:''}${p&&!n.missionEvent?`<p class="ui-note">Рекомендуемый уровень ${n.recommended||d.recommended}</p>`:''}${body}</section><footer class="ui-screen-footer event-footer">${exit}${primary}</footer>`;
}
