import {e,button,iconButton,frame,badge,meter,sectionLabel} from './atoms.js';
import {partArt,partCard,resource} from './molecules.js';
import {CATALOG} from '../catalog.js';
import {META_ACHIEVEMENTS,meta,START_BODIES,START_WEAPONS,START_ORGANS,starterAllowed,validLoadout} from '../systems/meta-progression.js';
import './meta-screens.css';
const footer=html=>`<footer class="ui-screen-footer">${html}</footer>`;
const short={claws:'Когти',seed:'Пулемёт',harpoon:'Гарпун',shield:'Щит'};
export function profileScreen(s,p){const m=meta(p);return `<section class="ui-screen-body meta-screen">${frame(`<div class="meta-avatar">${partArt('wanderer')}</div><div><h3>Странник</h3><p>Верхние сады</p></div>`,{className:'meta-identity'})}<div class="meta-stats">${resource('Забеги',m.runs,'clock')}${resource('Победы',m.wins,'target')}${resource('Жетоны',m.rerolls,'soul')}</div><p class="ui-note">Усиленных побед: ${m.overruns}. За каждую — 2 жетона перевыбора. Они сохраняются между забегами.</p>${sectionLabel('Достижения')}<div class="meta-achievements">${META_ACHIEVEMENTS.map(a=>{const done=p.achievements.includes(a.id),progress=done?a.goal:Math.min(a.goal,Math.max(a.progress(s),m.best?.[a.id]||0));return frame(`<div class="meta-achievement-art">${done?partArt(a.key):'<span aria-label="Скрытая деталь">'+({harpoon:'⚔',mirrorGland:'◈',reactor:'⬡',spring:'◇'})[a.key]+'</span>'}</div><div><h3>${e(a.name)}</h3><p>${done?e(CATALOG[a.key].name):'Неизвестная деталь'}</p>${done?badge('Открыто','mint'):meter(progress,a.goal,{label:a.name})}<small>${done?'В каталоге':progress+' / '+a.goal}</small></div>${iconButton('next','Подробнее',{action:'meta-achievement','data-id':a.id})}`,{className:'meta-achievement'});}).join('')}</div></section>${footer(button('Атлас',{action:'catalog'})+button('Подготовка',{action:'start',variant:'primary'}))}`;}
export function achievementScreen(s,p,id){const a=META_ACHIEVEMENTS.find(a=>a.id===id)||META_ACHIEVEMENTS[0],done=p.achievements.includes(a.id);return `<section class="ui-screen-body meta-screen">${sectionLabel(a.name)}${done?partArt(a.key,{className:'meta-large-art'}):'<p class="meta-mystery">?</p>'}<h3>${done?e(CATALOG[a.key].name):'Неизвестная деталь'}</h3><p>${e(a.description)}</p>${done?`<p>${e(CATALOG[a.key].description||CATALOG[a.key].trait)}</p>${badge('Открыто','mint')}`:'<p class="ui-note">После выполнения деталь откроется в каталоге и появится в инвентаре текущего забега.</p>'}</section>${footer(button('Назад',{action:'back'}))}`;}
export function loadoutScreen(p,params){const selected=validLoadout(p,params.choice);const grid=(keys,group)=>`<div class="meta-loadout-options">${keys.map(key=>`<div>${partCard({key,name:CATALOG[key].name,action:'starter-choice',id:group,selected:selected[group]===key,locked:!starterAllowed(p,key)})}<span>${selected[group]===key?'✓ ':''}${e(short[key]||CATALOG[key].name)}</span></div>`).join('')}</div>`;return `<section class="ui-screen-body meta-screen meta-loadout">${sectionLabel('1 · Корпус')}${grid(START_BODIES,'body')}${sectionLabel('2 · Оружие')}${grid(START_WEAPONS,'arm')}${sectionLabel('3 · Стартовый орган')}${grid(START_ORGANS,'organ')}</section>${footer(button('Начать',{action:'loadout-start',variant:'primary'}))}`;}
export function overrunScreen(s){return `<section class="ui-screen-body meta-screen"><h3>Победа уже сохранена</h3><p>Продержитесь ещё 30 секунд и уничтожьте двух усиленных элит. Каждые 4 секунды прибывает поддержка.</p>${frame('<h3>Награда: 2 жетона</h3><p>Накапливаются в профиле. Первый успех открывает гарпун и стартового Ловчего. Второй — Реактор и стартового Бастиона. Третий — стартовый орган.</p>',{className:'meta-selection-detail'})}<p class="ui-warning">При поражении жетоны не выдаются. Обычная победа и уже открытые детали сохраняются.</p></section>${footer(button('Уйти',{action:'home'})+button('Принять',{action:'overrun-start',variant:'primary'}))}`;}
