import {abilityArt,abilityTree} from './ability-tree.js';
import {e,attrs,icon,frame,button,iconButton,badge,meter} from './atoms.js';

// One canonical illustration per type, shared by inventory, rewards, HUD and atlas.
export const ART_KEYS=['wanderer','hunter','bastion','chimera','rootwalker','hecaton','claws','hammer','drill','whip','fangs','seed','needle','rocket','arc','acid','runner','universal','plated','regen','shield','armor','stabilizer','digestion','accelerator'];
const ORGAN_ART={returnNerve:'return-nerve',slime:'slime-sac',parasite:'parasite-womb',commonNerve:'common-nerve',outerStomach:'outer-stomach',reverseHeart:'reverse-heart'};
let atlasClipSerial=0;
// Authored row boundaries: the source sheet is not a uniform 5 x 5 grid.
const ATLAS_ROWS=[0,250,510,735,970,1254];
export function partArt(key,{className='',label=''}={}) {
  if(['harpoon','mirrorGland','reactor','spring'].includes(key))return `<span class="ui-part-art ${e(className)}" style="background-image:url('/assets/ui/items/${key}-v1.png');background-size:contain;background-position:center"${attrs({role:label?'img':null,'aria-label':label||null,'aria-hidden':label?null:'true'})}></span>`;
  if(key==='root')return `<span class="ui-part-art ${e(className)}" style="background-image:url('/assets/ui/items/root-leg-transparent-v1.png');background-size:contain;background-position:center"${attrs({role:label?'img':null,'aria-label':label||null,'aria-hidden':label?null:'true'})}></span>`;
  if(Object.hasOwn(ORGAN_ART,key))return `<span class="ui-part-art ui-part-art--organ ${e(className)}" style="background-image:url('/assets/ui/organs/${ORGAN_ART[key]}-v2.png')"${attrs({role:label?'img':null,'aria-label':label||null,'aria-hidden':label?null:'true'})}></span>`;
  const i=ART_KEYS.indexOf(key);
  if(i<0)return `<span class="ui-part-art ui-part-art--symbol ${e(className)}"${attrs({role:label?'img':null,'aria-label':label||null,'aria-hidden':label?null:'true'})}>${icon(({returnNerve:'back',slime:'cold',parasite:'leaf',commonNerve:'speed',outerStomach:'bag',reverseHeart:'health'})[key]||(key==='empty'?'plus':'soul'))}</span>`;
  const x=(i%5)*250.8,y=ATLAS_ROWS[Math.floor(i/5)],height=ATLAS_ROWS[Math.floor(i/5)+1]-y,clip='ui-atlas-clip-'+(++atlasClipSerial);
  return `<span class="ui-part-art ui-part-art--atlas ${e(className)}"${attrs({role:label?'img':null,'aria-label':label||null,'aria-hidden':label?null:'true'})}><svg viewBox="${x} ${y} 250.8 ${height}" aria-hidden="true" focusable="false"><defs><clipPath id="${clip}"><rect x="${x}" y="${y}" width="250.8" height="${height}"/></clipPath></defs><image href="/assets/ui/parts-atlas-transparent-v1.png" width="1254" height="1254" clip-path="url(#${clip})"/></svg></span>`;

}
export function stat(label,value,iconName){return `<div class="ui-stat">${iconName?icon(iconName):''}<span>${e(label)}</span><strong>${e(value)}</strong></div>`;}
export function resource(label,value,iconName='soul'){return `<span class="ui-resource">${icon(iconName)}<span><small>${e(label)}</small><strong>${e(value)}</strong></span></span>`;}
export function screenHeader(title,{subtitle='',backAction,closeAction}={}){return `<header class="ui-screen-header">${backAction?iconButton('back','Назад',{action:backAction}):''}<div>${subtitle?`<span class="ui-eyebrow">${e(subtitle)}</span>`:''}<h2>${e(title)}</h2></div>${closeAction?iconButton('close','Закрыть',{action:closeAction}):''}</header>`;}
export function partCard({key,name,tier='',note='',locked=false,selected=false,action='part',id,group,slot,groundId,compact=false}) {
  return `<button type="button" class="ui-frame ui-part-card ${locked?'is-locked':''} ${selected?'is-selected':''} ${compact?'is-compact':''}"${attrs({'data-action':action,'data-id':id,'data-key':key,'data-item-icon':'true','data-item-tier':tier,'data-item-note':note,'data-group':group,'data-slot':slot,'data-ground':groundId,'aria-label':name+(locked?' · ещё не открыто':'')})}>${partArt(key)}${locked?`<span class="ui-lock">${icon('lock')}</span>`:''}</button>`;
}
export function partSlot(part,{label,group,slot}={}){return `<div class="ui-slot"><span class="ui-slot-label">${e(label)}</span>${part?partCard({...part,group,slot,compact:true}):button('',{'aria-label':'Пусто · '+label,action:'empty-slot','data-group':group,'data-slot':slot,icon:'plus',className:'ui-empty-slot'})}</div>`;}
export function comparisonTable(rows){return `<div class="ui-comparison" role="region" aria-label="Сравнение характеристик"><table><thead><tr><th>Характеристика</th><th>Сейчас</th><th>После</th></tr></thead><tbody>${rows.map(r=>`<tr><th scope="row">${e(r.label)}</th><td>${e(r.before)}</td><td class="${r.changed?'is-'+(r.tone||'neutral'):''}">${r.changed?(r.tone==='positive'?'↑ ':r.tone==='negative'?'↓ ':'↔ '):''}${e(r.after)}</td></tr>`).join('')}</tbody></table></div>`;}
export function weightReadout(current,max,biomass){return frame(`<div class="ui-weight-line">${resource('Вес',`${current.toFixed(0)} / ${max.toFixed(0)}`,'bag')}${resource('Биомасса',biomass)}</div>${meter(current,max,{label:'Вес',className:current>max?'is-warning':''})}${current>max?'<p class="ui-warning">Перегруз · движение невозможно</p>':''}`,{className:'ui-weight'});}
export const branchIcon={melee:'enemy',ranged:'target',might:'enemy',tempo:'clock',projectiles:'target',fire:'fire',cold:'cold',electric:'speed',vitality:'health',motion:'pointer',summons:'leaf',synergy:'soul',minor:'plus'};
export function abilityRow(card,selected=false){return `<button type="button" class="ui-frame ui-ability-row ${selected?'is-selected':''}" data-action="select-ability" data-index="${card.index}" aria-expanded="${selected}" aria-controls="ability-detail">${abilityArt(card.id)}<span><small>${e(card.branchName)}${card.tier?' · '+e(card.tier):''}</small><strong>${e(card.name)}</strong></span>${icon('next')}</button>`;}
export function abilityDetail(card){return abilityTree(card);}

export function abilityCard(card){return `<article class="ui-frame ui-ability-card"><button class="ui-ability-select" type="button"${attrs({'data-action':'choose','data-index':card.index,'aria-label':`${card.name}. ${card.description}`})}>${abilityArt(card.id)}<span class="ui-ability-copy"><small>${e(card.branchName)} ${card.tier?`· ${e(card.tier)}`:''}</small><strong>${e(card.name)}</strong><span>${e(card.description)}</span></span>${icon('next')}</button>${card.nodes.length?`<details class="ui-branch-details"><summary>Ветка развития <span aria-hidden="true">＋</span></summary><p class="ui-note">${card.branch==='synergy'?'Синергия требует завершения обеих указанных веток.':'Основа → любое из двух улучшений → финал.'}</p><ol class="ui-branch-nodes">${card.nodes.map(n=>`<li class="is-${e(n.state)}"${attrs({'aria-current':n.id===card.id?'step':null})}><span>${n.state==='learned'?'✓':n.state==='available'?'◇':'○'}</span><span>${e(n.name)}<small>${n.state==='learned'?'Изучено':n.state==='available'?'Доступно':'Закрыто'}</small></span></li>`).join('')}</ol></details>`:''}</article>`;}
export function missionCard(m,{selected=false,complete=false,rewardCards='',index=0}={}){return frame(`<button type="button" class="ui-mission-trigger" data-action="mission-select" data-id="${e(m.id)}" aria-expanded="${selected}"><span class="ui-mission-number">${String(index+1).padStart(2,'0')}</span><span><strong>${e(m.name)}</strong><small>${icon('clock')}${m.duration/60} минут${complete?' · Выполнено':''}</small></span>${icon(complete?'check':selected?'down':'next')}</button>${selected?`<div class="ui-mission-body"><div class="ui-mission-image" aria-hidden="true"></div><div><p>${e(m.description)}</p><span class="ui-eyebrow">Награды</span><div class="ui-rewards">${rewardCards}</div></div></div>`:''}`,{className:`ui-mission ${selected?'is-selected':''}`});}
