import {DEFAULT_LANGUAGE, normalizeLanguage} from '../i18n/index.js';
export const SETTINGS_KEY='biomecha.settings.v1';
export const DEFAULT_SETTINGS=Object.freeze({language:DEFAULT_LANGUAGE,soundEnabled:false,effects:60,music:10,quality:'medium',fps:60,vibration:true,reducedMotion:false});
export function normalizeSettings(raw={}) {const value={...DEFAULT_SETTINGS};if(!raw||typeof raw!=='object')raw={};value.language=normalizeLanguage(raw.language);for(const key of ['effects','music'])if(Number.isFinite(raw[key]))value[key]=Math.max(0,Math.min(100,raw[key]));if(['low','medium','high'].includes(raw.quality))value.quality=raw.quality;if([30,60].includes(raw.fps))value.fps=raw.fps;for(const key of ['soundEnabled','vibration','reducedMotion'])if(typeof raw[key]==='boolean')value[key]=raw[key];return value;}
export function readSettings(storage){try{return normalizeSettings(JSON.parse(storage.getItem(SETTINGS_KEY))||{});}catch{return {...DEFAULT_SETTINGS};}}
export function createSettings(storage,{apply=()=>{},notify=()=>{}}={}){let value=readSettings(storage),audio;
  function update(key,next){value=normalizeSettings({...value,[key]:next});try{storage.setItem(SETTINGS_KEY,JSON.stringify(value));}catch{notify('Настройки действуют в этой сессии; сохранить их не удалось.');}apply(value);}
  function tick(){if(!value.soundEnabled||!value.effects)return;try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)return;audio??=new Audio();if(audio.state==='suspended')audio.resume();const oscillator=audio.createOscillator(),gain=audio.createGain(),now=audio.currentTime;oscillator.type='sine';oscillator.frequency.setValueAtTime(520,now);oscillator.frequency.exponentialRampToValueAtTime(360,now+.06);gain.gain.setValueAtTime(value.effects/100*.035,now);gain.gain.exponentialRampToValueAtTime(.0001,now+.07);oscillator.connect(gain).connect(audio.destination);oscillator.start(now);oscillator.stop(now+.08);oscillator.onended=()=>{oscillator.disconnect();gain.disconnect();};}catch{/* Audio is optional; UI remains usable. */}}
  return {get:()=>value,update,tick,apply:()=>apply(value),haptic:()=>{if(value.vibration&&typeof navigator.vibrate==='function')navigator.vibrate(20);}};
}
