import {createServer} from 'vite';
import {readFileSync,writeFileSync} from 'node:fs';
const baseline=process.argv.includes('--baseline');
const originals=new Set(['biome-view.js','enemy-assembly-view.js','environment-static-light.js','environment-surfaces.js','ground-sampling.js']);
const server=await createServer({server:{host:'127.0.0.1',port:baseline?5306:5296,strictPort:true,hmr:false,watch:null},plugins:[{name:'high60-proof',enforce:'pre',configureServer(server){server.middlewares.use('/_high60-result',(req,res)=>{if(req.method!=='POST'){res.statusCode=405;res.end();return;}let body='';req.on('data',chunk=>{body+=chunk;if(body.length>2000000)req.destroy();});req.on('end',()=>{try{const data=JSON.parse(body),name='auto-'+Date.now()+'-'+String(data.scenario).replace(/[^a-z]/g,'')+'.json';writeFileSync(new URL('./'+name,import.meta.url),JSON.stringify(data,null,2));res.end('saved');}catch{res.statusCode=400;res.end();}});});},transformIndexHtml(html){return html.replace('<head>','<head><script>Object.defineProperty(window,"devicePixelRatio",{value:2,configurable:true});</script>');},transform(source,id){
 if(baseline&&id.includes('/src/')&&originals.has(id.split('/').at(-1)))return readFileSync(new URL('./before/'+id.split('/').at(-1),import.meta.url),'utf8');
 if(baseline&&id.endsWith('/src/game-view.js'))return source.replace('modularEnemies.preload(s.time)','modularEnemies.preload?.(s.time)');
 if(!id.endsWith('/src/main.js'))return null;
 return source.replace("run=createWorldRun(profile,'survival',review?20317:undefined)","run=createWorldRun(review==='high60'?undefined:profile,'survival',review?20317:undefined)").replace('if(run.dead){','enemyReview?.afterSimulation?.();if(run.dead){').replace('enemyReview?.afterFrame?.({cpuMs:', 'enemyReview?.afterFrame?.({gpuInfo:view.frameInfo(),cpuMs:').replace('browserQA?.tick();', 'if(enemyReview?.finished)return;browserQA?.tick();').replace("if(review==='story-evidence')", "if(review==='high60'){const {prepare}=await import('/artifacts/high60-20260913/review.js');enemyReview=prepare(run,params,value=>Object.assign(movement,value),ui);document.body.dataset.screen='';}\nelse if(review==='story-evidence')");
}}]});await server.listen();server.printUrls();
