import {CATALOG} from '../../catalog.js';

export const RARITIES={common:'Обычная',uncommon:'Необычная',rare:'Эпическая',relic:'Легендарная'};
export const SETS={
 wanderer:{name:'Садовник',body:'body-worker',head:'head-worker',two:'Скорость движения +10%. Радиус притяжения опыта +50%.',three:'Сборщик: каждые 12 с притягивает опыт в радиусе 20 м.',details:'Первый сбор — через 12 с. Притягивает существующие сферы опыта, не создаёт новые и не собирает детали.'},
 hunter:{name:'Высотник',body:'body-scout',head:'head-optic',two:'Урон снарядов +20%. Дальность снарядов +20%.',three:'Точный залп: каждый третий залп снарядов наносит на 60% больше урона.',details:'Все снаряды третьего залпа усилены. Промах расходует залп. Осколки, рикошеты и периодический урон не считаются залпами.'},
 bastion:{name:'Каменщик',body:'body-heavy',head:'head-sentinel',two:'+1 пластина брони.',three:'Панцирь: блокирует одно попадание и восстанавливается 12 с.',details:'Кожух не требуется. Первый заряд — через 12 с. Панцирь расходуется после уклонения, до щитов органов и брони. Перестановка деталей не обновляет заряд.'},
 chimera:{name:'Мойщик',body:'body-jade',head:'head-mandible',two:'Ближний урон +20%. Дальность ближних атак +25%.',three:'Ближние попадания усиливают дальние атаки на 30% на 3 с, а дальние — ближние.',details:'Оба усиления могут действовать одновременно. Повторные попадания обновляют время, но не складывают процент. Дроны и вторичные эффекты не активируют бонус.'},
 rootwalker:{name:'Лесник',body:'body-seed',head:'head-crown',two:'+25 максимального HP.',three:'Живые ткани: непрерывно восстанавливает 1% максимального здоровья в секунду.',details:'Не требует Ремонтника. Полученный урон не прерывает восстановление. Складывается с остальными источниками регенерации и соблюдает запрет лечения.'},
 hecaton:{name:'Механик',body:'body-pod',head:'head-knight',two:'Время перезарядки −20%.',three:'Общий затвор: атаки трёх разных видов оружия перезаряжают все магазины. Не чаще раза в 8 с.',details:'Три вида оружия должны атаковать в течение 4 с; ближние атаки тоже считаются. Во время перезарядки бонуса тройка не накапливается. Не сбрасывает задержку между атаками и заряды органов.'},
 reactor:{name:'Электрик',body:'body-heavy',head:'head-sentinel',two:'Скорость атак всего оружия +15%.',three:'Разряд: каждые 12 с следующая атака оружием выпускает электрический импульс радиусом 4 м.',details:'Урон импульса — 80% урона запустившей его атаки, один раз на врага. Не проходит через стены и не запускает эффекты попадания. Работает независимо от особенности корпуса Электрика.'},
 broodmother:{name:'Пасечник',body:'body-broodmother-v3',head:'head-mandible',two:'Дополнительный дрон.',three:'Перехват снаряда ускоряет атаки и призыв роя на 40% на 4 с.',details:'Работает без корпуса Пасечника и «Колонии». Повторный перехват обновляет время ускорения.'},
};
export const SET_LEGS={wanderer:'leg-worker',hunter:'leg-jumper',bastion:'leg-guard',chimera:'leg-climber',rootwalker:'leg-root',hecaton:'leg-walker',broodmother:'leg-root'};
export function partMeta(p){return{setId:SETS[p.setId]?p.setId:null,rarity:RARITIES[p.rarity]?p.rarity:'common'};}
export const equipped=s=>[s.body,...(s.arms||[]),...(s.legs||[]),...(s.organs||[])].filter(Boolean);
export function setCounts(s){const groups={};for(const p of equipped(s)){const id=partMeta(p).setId;if(id)(groups[id]??=new Set()).add(CATALOG[p.key].kind);}return Object.fromEntries(Object.entries(groups).map(([id,g])=>[id,g.size]));}
