import {soulProc} from './soul-procs.js';
/** Ability definitions are also the UI contract; no DOM or equipment imports. */
export const BRANCHES={might:'Мощь',melee:'Ближний бой',ranged:'Дальний бой',tempo:'Темп атак',projectiles:'Снаряды',fire:'Огонь',cold:'Холод',electric:'Биоэлектричество',vitality:'Живучесть',motion:'Подвижность',summons:'Симбионты',metabolism:'Метаболизм'};
const rows={
 metabolism:[['Ферменты','Биомасса от переработки деталей +20%. Нужен желудок. Возврат затрат не усиливается.',{biomassYield:.2}],['Усвоение','Биомасса от деталей +20%. Получаемый опыт +10%.',{biomassYield:.2,xpGain:.1}],['Биокатализ','Ещё +20% биомассы от переработки деталей. Бонусы ветки складываются.',{biomassYield:.2}],['Полный цикл','Биомасса от деталей +40%. Получаемый опыт +15%. Вся ветка: +100% биомассы и +25% опыта.',{biomassYield:.4,xpGain:.15}]],
 melee:[['Хищные мышцы','Урон ближнего оружия +20%',{meleeDamage:.2}],['Уязвимые места','Шанс крита ближнего оружия +10 п.п.',{meleeCrit:.1}],['Натиск','Четвёртое попадание той же ближней рукой по одной цели: +50% урона. Смена цели или пауза 3 с сбрасывает серию.',{onslaught:true}],['Мясорубка','Убийство ближней атакой: скорость ближних атак +25% на 4 с. Повторное убийство обновляет время.',{meleeFrenzy:true}]],
 ranged:[['Прицельные нервы','Урон дальнего оружия +15%, включая дуговой орган',{rangedDamage:.15}],['Быстрая перезарядка','Время перезарядки дальнего оружия −20%',{rangedReload:.2}],['Точный прицел','Шанс крита дальнего оружия +10 п.п., включая дуговой орган',{rangedCrit:.1}],['Полный залп','Первый залп после полной перезарядки: +30% урона дальнего оружия. Начальный боезапас не усилен.',{fullSalvo:true}]],

 might:[['Мощные волокна','Урон всего оружия +10%',{damage:.1}],['Острые чувства','Шанс крита +10 п.п.',{crit:.1}],['Разрыв тканей','Множитель крита +0,5',{critPower:.5}],['Гипертрофия','Урон всего оружия +10%, скорость атак −10%',{damage:.1,rate:-.1}]],
 tempo:[['Быстрые связки','Скорость атак +15%',{rate:.15}],['Рефлексы','Скорость атак +15%',{rate:.15}],['Импульс','Скорость снарядов +20%, множитель крита всего оружия +0,25',{velocity:.2,critPower:.25}],['Эхо атаки','Каждая пятая атака руки повторяется через 0,15 с',{echo:true}]],
 projectiles:[['Двойной зародыш','Ещё 1 снаряд; урон снарядов −15%',{extra:1,projectileDamage:-.15}],['Сквозная игла','Пробивание прямых снарядов +1',{pierce:1}],['Разгон осколков','Скорость снарядов +25%, множитель крита всего оружия +0,25. Убийство прямой пулей выпускает 3 осколка по 35% урона; осколки не делятся повторно.',{velocity:.25,critPower:.25,splinter:true}],['Размножение','Ещё 2 снаряда; урон снарядов −20%',{extra:2,projectileDamage:-.2}]],
 fire:[['Жар','Попадание оружием: шанс поджечь 20%. Горение длится 3 с и наносит 20% урона попадания в секунду',{burn:true}],['Раскалённая кровь','Урон горения +50%',{burnDamage:.5}],['Долгое тление','Горение длится на 2 с дольше',{burnDuration:2}],['Пожар','Горение погибшего распространяется в радиусе 3 м',{spread:true}]],
 cold:[['Холодная кровь','Попадание оружием: шанс 20% замедлить врага на 30% на 2 с',{chill:true}],['Вечная мерзлота','Холод длится на 2 с дольше',{chillDuration:2}],['Хрупкость','Урон оружия по замедленным холодом врагам +20%',{brittle:.2}],['Кристаллизация','Третье наложение холода замораживает на 1 с; перезарядка 3 с. Боссов замедляет',{freeze:true}]],
 electric:[['Разряд','Каждая пятая атака руки: разряд на 50% её урона',{electric:true}],['Проводимость','Разряд переходит ещё на две цели в пределах 4 м',{chains:2}],['Напряжение','Урон разряда +50%',{electricDamage:.5}],['Грозовой орган','Разряд срабатывает каждой третьей атакой',{storm:true}]],
 vitality:[['Жизненная сила','Максимальное здоровье +1 деление; сохраняет число ран',{hp:1}],['Панцирь','+1 стальная пластина поверх здоровья; расходуется до здоровья',{armor:true}],['Восстановление','Восстанавливает 1 деление после 15 с без потери здоровья',{regen:true}],['Вторая жизнь','Один раз за забег: пережить смертельный удар с 1 делением здоровья и защитой на 2 с',{revive:true}]],
 motion:[['Лёгкий шаг','Скорость движения +10%',{speed:.1}],['Притяжение','Радиус притяжения опыта +50%',{pickup:.5}],['Скользящий панцирь','+1 стальная пластина при наличии брони; не больше ячеек здоровья',{movingArmor:true}],['Разбег','После 2 с непрерывного движения: скорость атак +20%; остановка снимает бонус',{running:true}]],
 summons:[['Спутник','Симбионт подлетает к врагам в радиусе 10 м и жалит; базовый урон 8',{summons:1}],['Стая','Ещё один симбионт',{summons:1}],['Рой','Скорость атак симбионтов +25%',{summonRate:.25}],['Симбиоз','Урон симбионтов +50%; их попадания применяют изученные огонь и холод',{summonDamage:.5,summonElements:true}]],
};
export const ABILITIES=Object.fromEntries(Object.entries(rows).flatMap(([branch,nodes])=>nodes.map(([name,description,bonus],i)=>{const id=`${branch}.${i}`;return[id,{id,branch,name,description,bonus,requires:i===0?[]:i===3?[`${branch}.1`,`${branch}.2`]:[`${branch}.0`],requireMode:'any',tier:i===0?1:i===3?3:2}];})));
for(const [id,name,description,requires,bonus] of [
 ['thermal','Термошок','Попадание руки по горящей замороженной цели: взрыв 3 м с уроном попадания, раз в 2 с на цель',['fire.3','cold.3'],{thermal:true}],
 ['plasma','Плазма','Разряды гарантированно поджигают',['fire.3','electric.3'],{plasma:true}],
 ['swarm','Резонанс роя','Каждая третья атака симбионта наносит двойной удар',['summons.3','tempo.3'],{swarm:true}],
])ABILITIES[id]={id,name,description,requires,bonus,branch:'synergy',requireMode:'all',tier:4};
export const FALLBACKS=Object.fromEntries([
 ['damage','Сила','Урон всего оружия +3%',{damage:.03}],['rate','Ритм','Скорость атак +3%',{rate:.03}],['pickup','Сбор','Радиус притяжения опыта +5%',{pickup:.05}],['speed','Шаг','Скорость движения +2% (общий предел +60%)',{speed:.02}],['critPower','Точность','Множитель крита +0,05',{critPower:.05}],
].map(([id,name,description,bonus])=>[`minor.${id}`,{id:`minor.${id}`,name,description,bonus,branch:'minor',tier:0,repeatable:true,requires:[]}])) ;
export const abilityById=id=>ABILITIES[id]||FALLBACKS[id];
export function createAbilities(){return{learned:[],minor:{},attacks:{},moving:0,echoes:[],companions:[],summonShots:[]};}
export function modifiers(s){const a=s.abilities;if(!a)return{};const out={};for(const id of a.learned){for(const [k,v]of Object.entries(ABILITIES[id]?.bonus||{}))out[k]=typeof v==='boolean'?v:(out[k]||0)+v;}for(const [id,n]of Object.entries(a.minor))for(const [k,v]of Object.entries(FALLBACKS[id]?.bonus||{}))out[k]=(out[k]||0)+v*n;if(out.running&&a.moving>=2)out.rate=(out.rate||0)+.2;return out;}
export function learn(s,id){const d=abilityById(id);if(!d)return false;if(d.repeatable)s.abilities.minor[id]=(s.abilities.minor[id]||0)+1;else{if(s.abilities.learned.includes(id))return false;s.abilities.learned.push(id);}return true;}
/** Primary attacks only. Echoes and secondary damage never increment counters. */
export function attackTriggers(s,part,w){const a=s.abilities,b=modifiers(s),count=a.attacks[part.id]=(a.attacks[part.id]||0)+1;return{electric:!!b.electric&&count%(b.storm?3:5)===0,echo:!!b.echo&&count%5===0};}
export function updateMotion(s,dt,moved){if(s.abilities){const before=s.abilities.moving;s.abilities.moving=moved?before+dt:0;if(before<2&&s.abilities.moving>=2&&modifiers(s).running)soulProc(s,'running',s.player);}}
